// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package documents

import (
	"encoding/json"
)

// DocumentValidationResultDto mirrors the iiko DTO of the same name.
type DocumentValidationResultDto struct {
	Valid                bool   `xml:"valid"`                          // read-only
	Warning              bool   `xml:"warning"`                        // read-only
	DocumentNumber       string `xml:"documentNumber,omitempty"`       // read-only
	OtherSuggestedNumber string `xml:"otherSuggestedNumber,omitempty"` // read-only
	ErrorMessage         string `xml:"errorMessage,omitempty"`         // read-only
	AdditionalInfo       string `xml:"additionalInfo,omitempty"`       // read-only
}

// IdCodeNameDto mirrors the iiko DTO of the same name.
type IdCodeNameDto struct {
	ID   string `xml:"id"`             // read-only
	Code string `xml:"code,omitempty"` // read-only
	Name string `xml:"name,omitempty"` // read-only
}

// IncomingInventoryDtoDocumentStatusValues are the documented values of IncomingInventoryDto.documentStatus.
var IncomingInventoryDtoDocumentStatusValues = []string{
	"NEW",
	"PROCESSED",
	"DELETED",
}

// IncomingInventoryDto mirrors the iiko DTO of the same name.
type IncomingInventoryDto struct {
	DocumentNumber         string                     `xml:"documentNumber,omitempty"`
	DateIncoming           string                     `xml:"dateIncoming,omitempty"`
	UseDefaultDocumentTime bool                       `xml:"useDefaultDocumentTime,omitempty"`
	Status                 string                     `xml:"status,omitempty"` // NEW PROCESSED DELETED
	AccountSurplusCode     string                     `xml:"accountSurplusCode,omitempty"`
	AccountShortageCode    string                     `xml:"accountShortageCode,omitempty"`
	StoreID                string                     `xml:"storeId,omitempty"`
	StoreCode              string                     `xml:"storeCode,omitempty"`
	ConceptionID           string                     `xml:"conceptionId,omitempty"`
	ConceptionCode         string                     `xml:"conceptionCode,omitempty"`
	Comment                string                     `xml:"comment,omitempty"`
	Items                  []IncomingInventoryItemDto `xml:"items"`
}

// IncomingInventoryItemDtoInventoryItemStatusValues are the documented values of IncomingInventoryItemDto.inventoryItemStatus.
var IncomingInventoryItemDtoInventoryItemStatusValues = []string{
	"NEW",
	"SAVE",
	"RECALC",
}

// IncomingInventoryItemDto mirrors the iiko DTO of the same name.
type IncomingInventoryItemDto struct {
	Status              string  `xml:"status,omitempty"`              // NEW SAVE RECALC
	RecalculationNumber int     `xml:"recalculationNumber,omitempty"` // read-only
	ProductID           string  `xml:"productId,omitempty"`
	ProductArticle      string  `xml:"productArticle,omitempty"`
	ContainerID         string  `xml:"containerId,omitempty"`
	ContainerCode       string  `xml:"containerCode,omitempty"`
	AmountContainer     float64 `xml:"amountContainer,omitempty"`
	AmountGross         float64 `xml:"amountGross,omitempty"`
	ProducerID          string  `xml:"producerId,omitempty"`
	Comment             string  `xml:"comment,omitempty"`
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported IncomingInventoryItemDto: encoding/xml cannot skip them per field.
func (x *IncomingInventoryItemDto) StripReadOnly() {
	var zeroRecalculationNumber int
	x.RecalculationNumber = zeroRecalculationNumber
}

// IncomingInventoryValidationResultDto is Root element is <incomingInventoryValidationResult>, a richer per-document-type validation result distinct fro…
type IncomingInventoryValidationResultDto struct {
	Valid                bool                                       `xml:"valid"`                    // read-only
	Warning              bool                                       `xml:"warning,omitempty"`        // read-only
	DocumentNumber       string                                     `xml:"documentNumber"`           // read-only
	OtherSuggestedNumber string                                     `xml:"otherSuggestedNumber"`     // read-only
	ErrorMessage         string                                     `xml:"errorMessage,omitempty"`   // read-only
	AdditionalInfo       string                                     `xml:"additionalInfo,omitempty"` // read-only
	Store                IdCodeNameDto                              `xml:"store,omitempty"`          // read-only
	Date                 string                                     `xml:"date,omitempty"`           // read-only
	Items                []IncomingInventoryValidationResultItemDto `xml:"items"`                    // read-only
}

// IncomingInventoryValidationResultItemDto mirrors the iiko DTO of the same name.
type IncomingInventoryValidationResultItemDto struct {
	Product          IdCodeNameDto `xml:"product"`          // read-only
	ExpectedAmount   float64       `xml:"expectedAmount"`   // read-only
	ExpectedSum      float64       `xml:"expectedSum"`      // read-only
	ActualAmount     float64       `xml:"actualAmount"`     // read-only
	DifferenceAmount float64       `xml:"differenceAmount"` // read-only
	DifferenceSum    float64       `xml:"differenceSum"`    // read-only
}

// IncomingInvoiceDtoDocumentStatusValues are the documented values of IncomingInvoiceDto.documentStatus.
var IncomingInvoiceDtoDocumentStatusValues = []string{
	"NEW",
	"PROCESSED",
	"DELETED",
}

// IncomingInvoiceDtoDistributionAlgorithmTypeValues are the documented values of IncomingInvoiceDto.distributionAlgorithmType.
var IncomingInvoiceDtoDistributionAlgorithmTypeValues = []string{
	"DISTRIBUTION_BY_SUM",
	"DISTRIBUTION_BY_AMOUNT",
	"DISTRIBUTION_NOT_SPECIFIED",
}

// IncomingInvoiceDto mirrors the iiko DTO of the same name.
type IncomingInvoiceDto struct {
	Items                   []IncomingInvoiceItemDto `xml:"items,omitempty"`
	ID                      string                   `xml:"id,omitempty"` // read-only
	Conception              string                   `xml:"conception,omitempty"`
	ConceptionCode          string                   `xml:"conceptionCode,omitempty"`
	Comment                 string                   `xml:"comment,omitempty"`
	DocumentNumber          string                   `xml:"documentNumber,omitempty"`
	DateIncoming            string                   `xml:"dateIncoming,omitempty"`
	Invoice                 string                   `xml:"invoice,omitempty"`
	DefaultStore            string                   `xml:"defaultStore,omitempty"`
	Supplier                string                   `xml:"supplier,omitempty"`
	DueDate                 string                   `xml:"dueDate,omitempty"`
	IncomingDate            string                   `xml:"incomingDate,omitempty"`
	UseDefaultDocumentTime  bool                     `xml:"useDefaultDocumentTime,omitempty"`
	Status                  string                   `xml:"status,omitempty"` // NEW PROCESSED DELETED
	IncomingDocumentNumber  string                   `xml:"incomingDocumentNumber,omitempty"`
	EmployeePassToAccount   string                   `xml:"employeePassToAccount,omitempty"`
	TransportInvoiceNumber  string                   `xml:"transportInvoiceNumber,omitempty"`
	LinkedOutgoingInvoiceID string                   `xml:"linkedOutgoingInvoiceId,omitempty"` // read-only
	DistributionAlgorithm   string                   `xml:"distributionAlgorithm,omitempty"`   // read-only; DISTRIBUTION_BY_SUM DISTRIBUTION_BY_AMOUNT DISTRIBUTION_NOT_SPECIFIED
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported IncomingInvoiceDto: encoding/xml cannot skip them per field.
func (x *IncomingInvoiceDto) StripReadOnly() {
	var zeroID string
	x.ID = zeroID
	var zeroLinkedOutgoingInvoiceID string
	x.LinkedOutgoingInvoiceID = zeroLinkedOutgoingInvoiceID
	var zeroDistributionAlgorithm string
	x.DistributionAlgorithm = zeroDistributionAlgorithm
}

// IncomingInvoiceItemDto mirrors the iiko DTO of the same name.
type IncomingInvoiceItemDto struct {
	IsAdditionalExpense      bool    `xml:"isAdditionalExpense,omitempty"` // read-only
	Amount                   float64 `xml:"amount,omitempty"`
	SupplierProduct          string  `xml:"supplierProduct,omitempty"`
	SupplierProductArticle   string  `xml:"supplierProductArticle,omitempty"`
	Product                  string  `xml:"product,omitempty"`
	ProductArticle           string  `xml:"productArticle,omitempty"`
	Producer                 string  `xml:"producer,omitempty"`
	Num                      int     `xml:"num"`
	ContainerID              string  `xml:"containerId,omitempty"`
	AmountUnit               string  `xml:"amountUnit,omitempty"`
	Sum                      float64 `xml:"sum"`
	VATPercent               float64 `xml:"vatPercent,omitempty"` // also spelled ndsPercent
	VATSum                   float64 `xml:"vatSum,omitempty"`
	PriceUnit                string  `xml:"priceUnit,omitempty"`
	Price                    float64 `xml:"price,omitempty"`
	PriceWithoutVAT          float64 `xml:"priceWithoutVat,omitempty"`
	Store                    string  `xml:"store,omitempty"`
	CustomsDeclarationNumber string  `xml:"customsDeclarationNumber,omitempty"`
	ActualAmount             float64 `xml:"actualAmount,omitempty"`
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported IncomingInvoiceItemDto: encoding/xml cannot skip them per field.
func (x *IncomingInvoiceItemDto) StripReadOnly() {
	var zeroIsAdditionalExpense bool
	x.IsAdditionalExpense = zeroIsAdditionalExpense
}

// InternalTransferDtoDocumentStatusValues are the documented values of InternalTransferDto.documentStatus.
var InternalTransferDtoDocumentStatusValues = []string{
	"NEW",
	"PROCESSED",
	"DELETED",
}

// InternalTransferDto mirrors the iiko DTO of the same name.
type InternalTransferDto struct {
	ID             string                    `json:"id,omitempty"`
	DateIncoming   string                    `json:"dateIncoming"`
	DocumentNumber string                    `json:"documentNumber,omitempty"`
	Status         string                    `json:"status"` // NEW PROCESSED DELETED
	ConceptionID   string                    `json:"conceptionId,omitempty"`
	Comment        string                    `json:"comment,omitempty"`
	StoreFromID    string                    `json:"storeFromId"`
	StoreToID      string                    `json:"storeToId"`
	Items          []InternalTransferItemDto `json:"items"`
}

// InternalTransferItemDto mirrors the iiko DTO of the same name.
type InternalTransferItemDto struct {
	Num           int     `json:"num,omitempty"` // read-only
	ProductID     string  `json:"productId"`
	Amount        float64 `json:"amount"`
	MeasureUnitID string  `json:"measureUnitId,omitempty"` // read-only
	ContainerID   string  `json:"containerId,omitempty"`
	Cost          float64 `json:"cost,omitempty"` // read-only
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x InternalTransferItemDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		ProductID   string  `json:"productId"`
		Amount      float64 `json:"amount"`
		ContainerID string  `json:"containerId,omitempty"`
	}{
		ProductID:   x.ProductID,
		Amount:      x.Amount,
		ContainerID: x.ContainerID,
	})
}

// OutgoingInvoiceDtoDocumentStatusValues are the documented values of OutgoingInvoiceDto.documentStatus.
var OutgoingInvoiceDtoDocumentStatusValues = []string{
	"NEW",
	"PROCESSED",
	"DELETED",
}

// OutgoingInvoiceDto mirrors the iiko DTO of the same name.
type OutgoingInvoiceDto struct {
	ID                      string                   `xml:"id,omitempty"` // read-only
	DocumentNumber          string                   `xml:"documentNumber,omitempty"`
	DateIncoming            string                   `xml:"dateIncoming,omitempty"`
	UseDefaultDocumentTime  bool                     `xml:"useDefaultDocumentTime,omitempty"`
	Status                  string                   `xml:"status,omitempty"` // NEW PROCESSED DELETED
	AccountToCode           string                   `xml:"accountToCode,omitempty"`
	RevenueAccountCode      string                   `xml:"revenueAccountCode,omitempty"`
	DefaultStoreID          string                   `xml:"defaultStoreId,omitempty"`
	DefaultStoreCode        string                   `xml:"defaultStoreCode,omitempty"`
	CounteragentID          string                   `xml:"counteragentId,omitempty"`
	CounteragentCode        string                   `xml:"counteragentCode,omitempty"`
	ConceptionID            string                   `xml:"conceptionId,omitempty"`
	ConceptionCode          string                   `xml:"conceptionCode,omitempty"`
	Comment                 string                   `xml:"comment,omitempty"`
	LinkedOutgoingInvoiceID string                   `xml:"linkedOutgoingInvoiceId,omitempty"` // read-only
	Items                   []OutgoingInvoiceItemDto `xml:"items"`
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported OutgoingInvoiceDto: encoding/xml cannot skip them per field.
func (x *OutgoingInvoiceDto) StripReadOnly() {
	var zeroID string
	x.ID = zeroID
	var zeroLinkedOutgoingInvoiceID string
	x.LinkedOutgoingInvoiceID = zeroLinkedOutgoingInvoiceID
}

// OutgoingInvoiceItemDto mirrors the iiko DTO of the same name.
type OutgoingInvoiceItemDto struct {
	ProductID       string  `xml:"productId,omitempty"`
	ProductArticle  string  `xml:"productArticle,omitempty"`
	StoreID         string  `xml:"storeId,omitempty"`
	StoreCode       string  `xml:"storeCode,omitempty"`
	ContainerID     string  `xml:"containerId,omitempty"`
	ContainerCode   string  `xml:"containerCode,omitempty"`
	Price           float64 `xml:"price"`
	PriceWithoutVAT float64 `xml:"priceWithoutVat,omitempty"` // read-only
	Amount          float64 `xml:"amount"`
	Sum             float64 `xml:"sum"`
	DiscountSum     float64 `xml:"discountSum,omitempty"`
	VATPercent      float64 `xml:"vatPercent,omitempty"`
	VATSum          float64 `xml:"vatSum,omitempty"`
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported OutgoingInvoiceItemDto: encoding/xml cannot skip them per field.
func (x *OutgoingInvoiceItemDto) StripReadOnly() {
	var zeroPriceWithoutVAT float64
	x.PriceWithoutVAT = zeroPriceWithoutVAT
}

// ProductionDocumentDtoDocumentStatusValues are the documented values of ProductionDocumentDto.documentStatus.
var ProductionDocumentDtoDocumentStatusValues = []string{
	"NEW",
	"PROCESSED",
	"DELETED",
}

// ProductionDocumentDto mirrors the iiko DTO of the same name.
type ProductionDocumentDto struct {
	Status         string                      `xml:"status,omitempty"` // NEW PROCESSED DELETED
	Conception     string                      `xml:"conception,omitempty"`
	ConceptionCode string                      `xml:"conceptionCode,omitempty"`
	Comment        string                      `xml:"comment,omitempty"`
	DocumentNumber string                      `xml:"documentNumber,omitempty"`
	DateIncoming   string                      `xml:"dateIncoming,omitempty"`
	StoreTo        string                      `xml:"storeTo,omitempty"`
	StoreFrom      string                      `xml:"storeFrom,omitempty"`
	Items          []ProductionDocumentItemDto `xml:"items,omitempty"`
}

// ProductionDocumentItemDto mirrors the iiko DTO of the same name.
type ProductionDocumentItemDto struct {
	Amount         float64 `xml:"amount,omitempty"`
	Product        string  `xml:"product,omitempty"`
	ProductArticle string  `xml:"productArticle,omitempty"`
	Num            int     `xml:"num,omitempty"`
	ContainerID    string  `xml:"containerId,omitempty"`
	AmountUnit     string  `xml:"amountUnit,omitempty"`
}

// ReturnedInvoiceDtoDocumentStatusValues are the documented values of ReturnedInvoiceDto.documentStatus.
var ReturnedInvoiceDtoDocumentStatusValues = []string{
	"NEW",
	"PROCESSED",
	"DELETED",
}

// ReturnedInvoiceDto is CONTRADICTION recorded as data: the returnedInvoice XSD declares <xs:element name="document" type="outgoingInv…
type ReturnedInvoiceDto struct {
	DocumentNumber         string                   `xml:"documentNumber,omitempty"`
	DateIncoming           string                   `xml:"dateIncoming,omitempty"`
	UseDefaultDocumentTime bool                     `xml:"useDefaultDocumentTime,omitempty"`
	Status                 string                   `xml:"status,omitempty"` // NEW PROCESSED DELETED
	IncomingInvoiceNumber  string                   `xml:"incomingInvoiceNumber"`
	IncomingInvoiceDate    string                   `xml:"incomingInvoiceDate"`
	StoreCostAffected      string                   `xml:"storeCostAffected,omitempty"`
	AccountToCode          string                   `xml:"accountToCode,omitempty"`
	DefaultStoreID         string                   `xml:"defaultStoreId,omitempty"`
	DefaultStoreCode       string                   `xml:"defaultStoreCode,omitempty"`
	CounteragentID         string                   `xml:"counteragentId,omitempty"`
	CounteragentCode       string                   `xml:"counteragentCode,omitempty"`
	ConceptionID           string                   `xml:"conceptionId,omitempty"`
	ConceptionCode         string                   `xml:"conceptionCode,omitempty"`
	Comment                string                   `xml:"comment,omitempty"`
	Items                  []ReturnedInvoiceItemDto `xml:"items"`
}

// ReturnedInvoiceItemDto mirrors the iiko DTO of the same name.
type ReturnedInvoiceItemDto struct {
	ProductID                string  `xml:"productId,omitempty"`
	ProductArticle           string  `xml:"productArticle,omitempty"`
	SupplierProduct          string  `xml:"supplierProduct,omitempty"`
	SupplierProductArticle   string  `xml:"supplierProductArticle,omitempty"`
	CustomsDeclarationNumber string  `xml:"customsDeclarationNumber,omitempty"`
	StoreID                  string  `xml:"storeId,omitempty"`
	StoreCode                string  `xml:"storeCode,omitempty"`
	ContainerID              string  `xml:"containerId,omitempty"`
	ContainerCode            string  `xml:"containerCode,omitempty"`
	Price                    float64 `xml:"price"`
	Amount                   float64 `xml:"amount"`
	Sum                      float64 `xml:"sum"`
	DiscountSum              float64 `xml:"discountSum,omitempty"`
	VATPercent               float64 `xml:"vatPercent,omitempty"`
	VATSum                   float64 `xml:"vatSum,omitempty"`
}

// SalesDocumentDtoDocumentStatusValues are the documented values of SalesDocumentDto.documentStatus.
var SalesDocumentDtoDocumentStatusValues = []string{
	"NEW",
	"PROCESSED",
	"DELETED",
}

// SalesDocumentDto mirrors the iiko DTO of the same name.
type SalesDocumentDto struct {
	Status             string                 `xml:"status,omitempty"` // NEW PROCESSED DELETED
	AccountToCode      string                 `xml:"accountToCode,omitempty"`
	RevenueAccountCode string                 `xml:"revenueAccountCode,omitempty"`
	DocumentNumber     string                 `xml:"documentNumber,omitempty"`
	DateIncoming       string                 `xml:"dateIncoming,omitempty"`
	Items              []SalesDocumentItemDto `xml:"items,omitempty"`
}

// SalesDocumentItemDto mirrors the iiko DTO of the same name.
type SalesDocumentItemDto struct {
	Amount         float64 `xml:"amount,omitempty"`
	StoreCode      string  `xml:"storeCode,omitempty"`
	StoreID        string  `xml:"storeId,omitempty"`
	ProductID      string  `xml:"productId,omitempty"`
	ProductArticle string  `xml:"productArticle,omitempty"`
	Sum            float64 `xml:"sum"`
	DiscountSum    float64 `xml:"discountSum,omitempty"`
	VATPercent     float64 `xml:"vatPercent,omitempty"`
	VATSum         float64 `xml:"vatSum,omitempty"`
}

// WriteoffDocumentDtoDocumentStatusValues are the documented values of WriteoffDocumentDto.documentStatus.
var WriteoffDocumentDtoDocumentStatusValues = []string{
	"NEW",
	"PROCESSED",
	"DELETED",
}

// WriteoffDocumentDto mirrors the iiko DTO of the same name.
type WriteoffDocumentDto struct {
	ID                           string                    `json:"id,omitempty"`
	DateIncoming                 string                    `json:"dateIncoming"`
	DocumentNumber               string                    `json:"documentNumber,omitempty"`
	Status                       string                    `json:"status"` // NEW PROCESSED DELETED
	ConceptionID                 string                    `json:"conceptionId,omitempty"`
	Comment                      string                    `json:"comment,omitempty"`
	StoreID                      string                    `json:"storeId"`
	AccountID                    string                    `json:"accountId"`
	ExternalOutgoingInvoiceID    string                    `json:"externalOutgoingInvoiceId,omitempty"`    // read-only
	ExternalProductionDocumentID string                    `json:"externalProductionDocumentId,omitempty"` // read-only
	Items                        []WriteoffDocumentItemDto `json:"items"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x WriteoffDocumentDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		ID             string                    `json:"id,omitempty"`
		DateIncoming   string                    `json:"dateIncoming"`
		DocumentNumber string                    `json:"documentNumber,omitempty"`
		Status         string                    `json:"status"`
		ConceptionID   string                    `json:"conceptionId,omitempty"`
		Comment        string                    `json:"comment,omitempty"`
		StoreID        string                    `json:"storeId"`
		AccountID      string                    `json:"accountId"`
		Items          []WriteoffDocumentItemDto `json:"items"`
	}{
		ID:             x.ID,
		DateIncoming:   x.DateIncoming,
		DocumentNumber: x.DocumentNumber,
		Status:         x.Status,
		ConceptionID:   x.ConceptionID,
		Comment:        x.Comment,
		StoreID:        x.StoreID,
		AccountID:      x.AccountID,
		Items:          x.Items,
	})
}

// WriteoffDocumentItemDto mirrors the iiko DTO of the same name.
type WriteoffDocumentItemDto struct {
	Num           int     `json:"num,omitempty"` // read-only
	ProductID     string  `json:"productId"`
	ProductSizeID string  `json:"productSizeId,omitempty"`
	AmountFactor  float64 `json:"amountFactor,omitempty"`
	Amount        float64 `json:"amount"`
	MeasureUnitID string  `json:"measureUnitId,omitempty"` // read-only
	ContainerID   string  `json:"containerId,omitempty"`
	Cost          float64 `json:"cost,omitempty"` // read-only
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x WriteoffDocumentItemDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		ProductID     string  `json:"productId"`
		ProductSizeID string  `json:"productSizeId,omitempty"`
		AmountFactor  float64 `json:"amountFactor,omitempty"`
		Amount        float64 `json:"amount"`
		ContainerID   string  `json:"containerId,omitempty"`
	}{
		ProductID:     x.ProductID,
		ProductSizeID: x.ProductSizeID,
		AmountFactor:  x.AmountFactor,
		Amount:        x.Amount,
		ContainerID:   x.ContainerID,
	})
}
