// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package suppliers

// SupplierPriceListItemDto mirrors the iiko DTO of the same name.
type SupplierPriceListItemDto struct {
	NativeProduct           string  `xml:"nativeProduct,omitempty"`           // read-only
	NativeProductCode       string  `xml:"nativeProductCode,omitempty"`       // read-only
	NativeProductNum        string  `xml:"nativeProductNum,omitempty"`        // read-only
	NativeProductName       string  `xml:"nativeProductName,omitempty"`       // read-only
	SupplierProduct         string  `xml:"supplierProduct,omitempty"`         // read-only
	SupplierProductCode     string  `xml:"supplierProductCode,omitempty"`     // read-only
	SupplierProductNum      string  `xml:"supplierProductNum,omitempty"`      // read-only
	SupplierProductName     string  `xml:"supplierProductName,omitempty"`     // read-only
	CostPrice               float64 `xml:"costPrice,omitempty"`               // read-only
	AllowablePriceDeviation float64 `xml:"allowablePriceDeviation,omitempty"` // read-only
	Container               string  `xml:"container,omitempty"`               // read-only
}
