// Package orders paths. Every path is a constant here; none appears in a method body.

package orders

const (
	addCustomerOrder                                 = "/api/1/order/add_customer"
	addItemsDeliveries                               = "/api/1/deliveries/add_items"
	addItemsOrder                                    = "/api/1/order/add_items"
	addItemsReserve                                  = "/api/1/reserve/add_items"
	addPaymentsDeliveries                            = "/api/1/deliveries/add_payments"
	addPaymentsOrder                                 = "/api/1/order/add_payments"
	addPaymentsReserve                               = "/api/1/reserve/add_payments"
	cancelConfirmationDeliveries                     = "/api/1/deliveries/cancel_confirmation"
	cancelDeliveries                                 = "/api/1/deliveries/cancel"
	cancelOrder                                      = "/api/1/order/cancel"
	cancelReserve                                    = "/api/1/reserve/cancel"
	changeCommentDeliveries                          = "/api/1/deliveries/change_comment"
	changeCompleteBeforeDeliveries                   = "/api/1/deliveries/change_complete_before"
	changeDeliveryPointDeliveries                    = "/api/1/deliveries/change_delivery_point"
	changeDriverInfoDeliveries                       = "/api/1/deliveries/change_driver_info"
	changeEstimatedStartTimeReserve                  = "/api/1/reserve/change_estimated_start_time"
	changeExternalDataDeliveries                     = "/api/1/deliveries/change_external_data"
	changeExternalDataOrder                          = "/api/1/order/change_external_data"
	changeItemsReserve                               = "/api/1/reserve/change_items"
	changeOperatorDeliveries                         = "/api/1/deliveries/change_operator"
	changePaymentsDeliveries                         = "/api/1/deliveries/change_payments"
	changePaymentsOrder                              = "/api/1/order/change_payments"
	changeServiceTypeDeliveries                      = "/api/1/deliveries/change_service_type"
	changeTablesReserve                              = "/api/1/reserve/change_tables"
	closeDeliveries                                  = "/api/1/deliveries/close"
	closeOrder                                       = "/api/1/order/close"
	commitDeliveriesDrafts                           = "/api/1/deliveries/drafts/commit"
	confirmDeliveries                                = "/api/1/deliveries/confirm"
	createDeliveries                                 = "/api/1/deliveries/create"
	createDeliveriesDrafts                           = "/api/1/deliveries/drafts/create"
	createOrder                                      = "/api/1/order/create"
	createReserve                                    = "/api/1/reserve/create"
	deleteDeliveriesDrafts                           = "/api/1/deliveries/drafts/delete"
	getDeliveriesByDeliveryDateAndPhone              = "/api/1/deliveries/by_delivery_date_and_phone"
	getDeliveriesByDeliveryDateAndSourceKeyAndFilter = "/api/1/deliveries/by_delivery_date_and_source_key_and_filter"
	getDeliveriesByDeliveryDateAndStatus             = "/api/1/deliveries/by_delivery_date_and_status"
	getDeliveriesByID                                = "/api/1/deliveries/by_id"
	getDeliveriesByRevision                          = "/api/1/deliveries/by_revision"
	getDeliveriesDraftsByFilter                      = "/api/1/deliveries/drafts/by_filter"
	getDeliveriesDraftsByID                          = "/api/1/deliveries/drafts/by_id"
	getDeliveriesHistoryByDeliveryDateAndPhone       = "/api/1/deliveries/history/by_delivery_date_and_phone"
	getOrderByID                                     = "/api/1/order/by_id"
	getOrderByTable                                  = "/api/1/order/by_table"
	getReserveAvailableOrganizations                 = "/api/1/reserve/available_organizations"
	getReserveAvailableRestaurantSections            = "/api/1/reserve/available_restaurant_sections"
	getReserveAvailableTerminalGroups                = "/api/1/reserve/available_terminal_groups"
	getReserveRestaurantSectionsWorkload             = "/api/1/reserve/restaurant_sections_workload"
	getReserveStatusByID                             = "/api/1/reserve/status_by_id"
	initOrderByPosOrder                              = "/api/1/order/init_by_posOrder"
	initOrderByTable                                 = "/api/1/order/init_by_table"
	lockDeliveriesDrafts                             = "/api/1/deliveries/drafts/lock"
	printDeliveryBill                                = "/api/1/deliveries/print_delivery_bill"
	printOrderBill                                   = "/api/1/order/print_bill"
	saveDeliveriesDrafts                             = "/api/1/deliveries/drafts/save"
	unlockDeliveriesDrafts                           = "/api/1/deliveries/drafts/unlock"
	updateOrderDeliveryStatusDeliveries              = "/api/1/deliveries/update_order_delivery_status"
	updateOrderProblemDeliveries                     = "/api/1/deliveries/update_order_problem"
	updateTrackingLinkDeliveries                     = "/api/1/deliveries/update_tracking_link"
)
