// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package pricing

import (
	"encoding/json"
)

// ClientPriceCategoryDto mirrors the iiko DTO of the same name.
type ClientPriceCategoryDto struct {
	ID                 string             `json:"id,omitempty"` // read-only
	Name               string             `json:"name,omitempty"`
	Deleted            bool               `json:"deleted,omitempty"` // read-only
	Code               string             `json:"code,omitempty"`
	AssignableManually bool               `json:"assignableManually,omitempty"`
	PricingStrategy    PricingStrategyDto `json:"pricingStrategy,omitempty"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x ClientPriceCategoryDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		Name               string             `json:"name,omitempty"`
		Code               string             `json:"code,omitempty"`
		AssignableManually bool               `json:"assignableManually,omitempty"`
		PricingStrategy    PricingStrategyDto `json:"pricingStrategy,omitempty"`
	}{
		Name:               x.Name,
		Code:               x.Code,
		AssignableManually: x.AssignableManually,
		PricingStrategy:    x.PricingStrategy,
	})
}

// IncludeForCategoryDto mirrors the iiko DTO of the same name.
type IncludeForCategoryDto struct {
	CategoryID string `json:"categoryId,omitempty"`
	Include    bool   `json:"include,omitempty"`
}

// MenuChangeDocumentDtoDocumentStatusValues are the documented values of MenuChangeDocumentDto.documentStatus.
var MenuChangeDocumentDtoDocumentStatusValues = []string{
	"NEW",
	"PROCESSED",
	"DELETED",
}

// MenuChangeDocumentDto mirrors the iiko DTO of the same name.
type MenuChangeDocumentDto struct {
	ID                 string                      `json:"id,omitempty"`
	DateIncoming       string                      `json:"dateIncoming,omitempty"`
	DocumentNumber     string                      `json:"documentNumber,omitempty"`
	Status             string                      `json:"status,omitempty"` // NEW PROCESSED DELETED
	Comment            string                      `json:"comment,omitempty"`
	ShortName          string                      `json:"shortName,omitempty"`
	DeletePreviousMenu bool                        `json:"deletePreviousMenu,omitempty"`
	ScheduleID         string                      `json:"scheduleId,omitempty"`
	Schedule           PeriodScheduleDto           `json:"schedule,omitempty"` // read-only
	DateTo             string                      `json:"dateTo,omitempty"`
	Items              []MenuChangeDocumentItemDto `json:"items,omitempty"`
	TaxCategoryID      string                      `json:"taxCategoryId,omitempty"`
	TaxCategoryEnabled bool                        `json:"taxCategoryEnabled,omitempty"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x MenuChangeDocumentDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		ID                 string                      `json:"id,omitempty"`
		DateIncoming       string                      `json:"dateIncoming,omitempty"`
		DocumentNumber     string                      `json:"documentNumber,omitempty"`
		Status             string                      `json:"status,omitempty"`
		Comment            string                      `json:"comment,omitempty"`
		ShortName          string                      `json:"shortName,omitempty"`
		DeletePreviousMenu bool                        `json:"deletePreviousMenu,omitempty"`
		ScheduleID         string                      `json:"scheduleId,omitempty"`
		DateTo             string                      `json:"dateTo,omitempty"`
		Items              []MenuChangeDocumentItemDto `json:"items,omitempty"`
		TaxCategoryID      string                      `json:"taxCategoryId,omitempty"`
		TaxCategoryEnabled bool                        `json:"taxCategoryEnabled,omitempty"`
	}{
		ID:                 x.ID,
		DateIncoming:       x.DateIncoming,
		DocumentNumber:     x.DocumentNumber,
		Status:             x.Status,
		Comment:            x.Comment,
		ShortName:          x.ShortName,
		DeletePreviousMenu: x.DeletePreviousMenu,
		ScheduleID:         x.ScheduleID,
		DateTo:             x.DateTo,
		Items:              x.Items,
		TaxCategoryID:      x.TaxCategoryID,
		TaxCategoryEnabled: x.TaxCategoryEnabled,
	})
}

// MenuChangeDocumentItemDto mirrors the iiko DTO of the same name.
type MenuChangeDocumentItemDto struct {
	Num                  int                     `json:"num,omitempty"` // read-only
	DepartmentID         string                  `json:"departmentId,omitempty"`
	ProductID            string                  `json:"productId,omitempty"`
	ProductSizeID        string                  `json:"productSizeId,omitempty"`
	Including            bool                    `json:"including,omitempty"`
	Price                float64                 `json:"price,omitempty"`
	DishOfDay            bool                    `json:"dishOfDay,omitempty"`
	FlyerProgram         bool                    `json:"flyerProgram,omitempty"`
	IncludeForCategories []IncludeForCategoryDto `json:"includeForCategories,omitempty"`
	PricesForCategories  []PriceForCategoryDto   `json:"pricesForCategories,omitempty"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x MenuChangeDocumentItemDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		DepartmentID         string                  `json:"departmentId,omitempty"`
		ProductID            string                  `json:"productId,omitempty"`
		ProductSizeID        string                  `json:"productSizeId,omitempty"`
		Including            bool                    `json:"including,omitempty"`
		Price                float64                 `json:"price,omitempty"`
		DishOfDay            bool                    `json:"dishOfDay,omitempty"`
		FlyerProgram         bool                    `json:"flyerProgram,omitempty"`
		IncludeForCategories []IncludeForCategoryDto `json:"includeForCategories,omitempty"`
		PricesForCategories  []PriceForCategoryDto   `json:"pricesForCategories,omitempty"`
	}{
		DepartmentID:         x.DepartmentID,
		ProductID:            x.ProductID,
		ProductSizeID:        x.ProductSizeID,
		Including:            x.Including,
		Price:                x.Price,
		DishOfDay:            x.DishOfDay,
		FlyerProgram:         x.FlyerProgram,
		IncludeForCategories: x.IncludeForCategories,
		PricesForCategories:  x.PricesForCategories,
	})
}

// PeriodDto mirrors the iiko DTO of the same name.
type PeriodDto struct {
	Begin      string `json:"begin,omitempty"`      // read-only
	End        string `json:"end,omitempty"`        // read-only
	DaysOfWeek []int  `json:"daysOfWeek,omitempty"` // read-only
}

// PeriodScheduleDto is Shape reconciled across domains. The docs for /resto/api/v2/documents/menuChange, /resto/api/v2/documents/menu…
type PeriodScheduleDto struct {
	ID      string                  `json:"id,omitempty"` // read-only
	Name    string                  `json:"name,omitempty"`
	Deleted bool                    `json:"deleted,omitempty"` // read-only
	Periods []PeriodScheduleItemDto `json:"periods,omitempty"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x PeriodScheduleDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		Name    string                  `json:"name,omitempty"`
		Periods []PeriodScheduleItemDto `json:"periods,omitempty"`
	}{
		Name:    x.Name,
		Periods: x.Periods,
	})
}

// PeriodScheduleItemDtoDayOfWeekValues are the documented values of PeriodScheduleItemDto.DayOfWeek.
var PeriodScheduleItemDtoDayOfWeekValues = []string{
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
}

// PeriodScheduleItemDto mirrors the iiko DTO of the same name.
type PeriodScheduleItemDto struct {
	Begin      string `json:"begin,omitempty"`
	End        string `json:"end,omitempty"`
	DaysOfWeek []int  `json:"daysOfWeek,omitempty"`
}

// PriceForCategoryDto mirrors the iiko DTO of the same name.
type PriceForCategoryDto struct {
	CategoryID string  `json:"categoryId,omitempty"`
	Price      float64 `json:"price,omitempty"`
}

// PricingStrategyDtoPricingStrategyTypeValues are the documented values of PricingStrategyDto.PricingStrategyType.
var PricingStrategyDtoPricingStrategyTypeValues = []string{
	"ABSOLUTE_VALUE",
	"PERCENT",
}

// PricingStrategyDto mirrors the iiko DTO of the same name.
type PricingStrategyDto struct {
	Type    string  `json:"type,omitempty"` // ABSOLUTE_VALUE PERCENT
	Delta   float64 `json:"delta,omitempty"`
	Percent float64 `json:"percent,omitempty"`
}

// ProductPriceDto mirrors the iiko DTO of the same name.
type ProductPriceDto struct {
	DepartmentID  string                `json:"departmentId,omitempty"`  // read-only
	ProductID     string                `json:"productId,omitempty"`     // read-only
	ProductSizeID string                `json:"productSizeId,omitempty"` // read-only
	Prices        []ProductPriceItemDto `json:"prices,omitempty"`        // read-only
}

// ProductPriceItemDto mirrors the iiko DTO of the same name.
type ProductPriceItemDto struct {
	DateFrom             string                  `json:"dateFrom,omitempty"`             // read-only
	DateTo               string                  `json:"dateTo,omitempty"`               // read-only
	Price                float64                 `json:"price,omitempty"`                // read-only
	IncludeForCategories []IncludeForCategoryDto `json:"includeForCategories,omitempty"` // read-only
	PricesForCategories  []PriceForCategoryDto   `json:"pricesForCategories,omitempty"`  // read-only
	Included             bool                    `json:"included,omitempty"`             // read-only
	DishOfDay            bool                    `json:"dishOfDay,omitempty"`            // read-only
	FlyerProgram         bool                    `json:"flyerProgram,omitempty"`         // read-only
	DocumentID           string                  `json:"documentId,omitempty"`           // read-only
	Schedule             PeriodScheduleDto       `json:"schedule,omitempty"`             // read-only
	TaxCategoryID        string                  `json:"taxCategoryId,omitempty"`        // read-only
	TaxCategoryEnabled   bool                    `json:"taxCategoryEnabled,omitempty"`   // read-only
}
