// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package corporation

// AccountDtoAccountTypeValues are the documented values of AccountDto.AccountType.
var AccountDtoAccountTypeValues = []string{
	"CASH",
	"ACCOUNTS_RECEIVABLE",
	"DEBTS_OF_EMPLOYEES",
	"CURRENT_ASSET",
	"OTHER_CURRENT_ASSET",
	"INVENTORY_ASSETS",
	"EMPLOYEES_LIABILITY",
	"ACCOUNTS_PAYABLE",
	"CLIENTS_LIABILITY",
	"OTHER_CURRENT_LIABILITY",
	"LONG_TERM_LIABILITY",
	"EQUITY",
	"COST_OF_GOODS_SOLD",
	"INCOME",
	"EXPENSES",
	"OTHER_INCOME",
	"OTHER_EXPENSES",
}

// AccountDto mirrors the iiko DTO of the same name.
type AccountDto struct {
	ID                        string `json:"id,omitempty"`                        // read-only
	AccountParentID           string `json:"accountParentId,omitempty"`           // read-only
	ParentCorporateID         string `json:"parentCorporateId,omitempty"`         // read-only
	Code                      string `json:"code,omitempty"`                      // read-only
	Deleted                   bool   `json:"deleted,omitempty"`                   // read-only
	Name                      string `json:"name,omitempty"`                      // read-only
	Type                      string `json:"type,omitempty"`                      // read-only; CASH ACCOUNTS_RECEIVABLE DEBTS_OF_EMPLOYEES CURRENT_ASSET OTHER_CURRENT_ASSET INVENTORY_ASSETS EMPLOYEES_LIABILITY ACCOUNTS_PAYABLE CLIENTS_LIABILITY OTHER_CURRENT_LIABILITY LONG_TERM_LIABILITY EQUITY COST_OF_GOODS_SOLD INCOME EXPENSES OTHER_INCOME OTHER_EXPENSES
	System                    bool   `json:"system,omitempty"`                    // read-only
	CustomTransactionsAllowed bool   `json:"customTransactionsAllowed,omitempty"` // read-only
	RootType                  string `json:"rootType,omitempty"`                  // read-only
}

// CorporateItemDtoDepartmentTypeValues are the documented values of CorporateItemDto.DepartmentType.
var CorporateItemDtoDepartmentTypeValues = []string{
	"CORPORATION",
	"JURPERSON",
	"ORGDEVELOPMENT",
	"DEPARTMENT",
	"MANUFACTURE",
	"CENTRALSTORE",
	"CENTRALOFFICE",
	"SALEPOINT",
	"STORE",
}

// CorporateItemDto mirrors the iiko DTO of the same name.
type CorporateItemDto struct {
	ID                               string                           `xml:"id"`                 // read-only
	ParentID                         string                           `xml:"parentId,omitempty"` // read-only
	Code                             string                           `xml:"code,omitempty"`
	Name                             string                           `xml:"name,omitempty"`
	Type                             string                           `xml:"type"`                                       // read-only; CORPORATION JURPERSON ORGDEVELOPMENT DEPARTMENT MANUFACTURE CENTRALSTORE CENTRALOFFICE SALEPOINT STORE
	TaxpayerIDNumber                 string                           `xml:"taxpayerIdNumber"`                           // read-only
	JurPersonAdditionalPropertiesDto JurPersonAdditionalPropertiesDto `xml:"jurPersonAdditionalPropertiesDto,omitempty"` // read-only
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported CorporateItemDto: encoding/xml cannot skip them per field.
func (x *CorporateItemDto) StripReadOnly() {
	var zeroID string
	x.ID = zeroID
	var zeroParentID string
	x.ParentID = zeroParentID
	var zeroType string
	x.Type = zeroType
	var zeroTaxpayerIDNumber string
	x.TaxpayerIDNumber = zeroTaxpayerIDNumber
	var zeroJurPersonAdditionalPropertiesDto JurPersonAdditionalPropertiesDto
	x.JurPersonAdditionalPropertiesDto = zeroJurPersonAdditionalPropertiesDto
}

// CorporationSettingsDtoVatAccountingValues are the documented values of CorporationSettingsDto.VatAccounting.
var CorporationSettingsDtoVatAccountingValues = []string{
	"VAT_INCLUDED_IN_PRICE",
	"VAT_NOT_INCLUDED_IN_PRICE",
}

// CorporationSettingsDto mirrors the iiko DTO of the same name.
type CorporationSettingsDto struct {
	VATAccounting string `json:"vatAccounting,omitempty"` // VAT_INCLUDED_IN_PRICE VAT_NOT_INCLUDED_IN_PRICE
}

// EntityListItemDtoOrderServiceTypeValues are the documented values of EntityListItemDto.OrderServiceType.
var EntityListItemDtoOrderServiceTypeValues = []string{
	"COMMON",
	"DELIVERY_BY_COURIER",
	"DELIVERY_PICKUP",
}

// EntityListItemDto mirrors the iiko DTO of the same name.
type EntityListItemDto struct {
	ID                    string  `json:"id,omitempty"`                    // read-only
	RootType              string  `json:"rootType,omitempty"`              // read-only; Account AccountingCategory AlcoholClass AllergenGroup AttendanceType Conception CookingPlaceType DiscountType MeasureUnit OrderType PaymentType ProductCategory ProductScale ProductSize ScheduleType TaxCategory
	Deleted               bool    `json:"deleted,omitempty"`               // read-only
	Code                  string  `json:"code,omitempty"`                  // read-only
	Name                  string  `json:"name,omitempty"`                  // read-only
	OrderServiceType      string  `json:"orderServiceType,omitempty"`      // read-only; COMMON DELIVERY_BY_COURIER DELIVERY_PICKUP
	DefaultForServiceType string  `json:"defaultForServiceType,omitempty"` // read-only
	ShortName             string  `json:"shortName,omitempty"`             // read-only
	VATPercent            float64 `json:"vatPercent,omitempty"`            // read-only
}

// GroupDtoGroupServiceModeDtoValues are the documented values of GroupDto.GroupServiceModeDto.
var GroupDtoGroupServiceModeDtoValues = []string{
	"FAST_FOOD",
	"TABLE_SERVICE",
	"PETROLEUM",
}

// GroupDto mirrors the iiko DTO of the same name.
type GroupDto struct {
	ID                     string           `xml:"id"` // read-only
	Name                   string           `xml:"name"`
	DepartmentID           string           `xml:"departmentId,omitempty"` // read-only
	GroupServiceMode       string           `xml:"groupServiceMode"`       // FAST_FOOD TABLE_SERVICE PETROLEUM
	PointOfSaleDtoes       []PointOfSaleDto `xml:"pointOfSaleDtoes"`       // read-only
	RestaurantSectionInfos []IdNameDto      `xml:"restaurantSectionInfos"` // read-only
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported GroupDto: encoding/xml cannot skip them per field.
func (x *GroupDto) StripReadOnly() {
	var zeroID string
	x.ID = zeroID
	var zeroDepartmentID string
	x.DepartmentID = zeroDepartmentID
	var zeroPointOfSaleDtoes []PointOfSaleDto
	x.PointOfSaleDtoes = zeroPointOfSaleDtoes
	var zeroRestaurantSectionInfos []IdNameDto
	x.RestaurantSectionInfos = zeroRestaurantSectionInfos
}

// IdNameDto mirrors the iiko DTO of the same name.
type IdNameDto struct {
	ID   string `xml:"id"`   // read-only
	Name string `xml:"name"` // read-only
}

// JurPersonAdditionalPropertiesDto mirrors the iiko DTO of the same name.
type JurPersonAdditionalPropertiesDto struct {
	TaxpayerID                         string              `xml:"taxpayerId,omitempty"`
	AccountingReasonCode               string              `xml:"accountingReasonCode,omitempty"`
	BusinessClassificationCode         string              `xml:"businessClassificationCode,omitempty"`
	EconomicActivityClassificationCode string              `xml:"economicActivityClassificationCode,omitempty"`
	Iban                               string              `xml:"iban,omitempty"`
	SwiftBic                           string              `xml:"swiftBic,omitempty"`
	RegistrationNumber                 string              `xml:"registrationNumber,omitempty"`
	Address                            string              `xml:"address,omitempty"`
	SettlementAccount                  string              `xml:"settlementAccount,omitempty"`
	Bik                                string              `xml:"bik,omitempty"`
	Bank                               string              `xml:"bank,omitempty"`
	BankCity                           string              `xml:"bankCity,omitempty"`
	CorrespondentAccount               string              `xml:"correspondentAccount,omitempty"`
	Phone                              string              `xml:"phone,omitempty"`
	GLN                                string              `xml:"gln,omitempty"`
	Description                        string              `xml:"description,omitempty"`
	LegalAddressDto                    LegalAddressDto     `xml:"legalAddressDto,omitempty"`
	OfficialEmployees                  OfficialEmployeeDto `xml:"officialEmployees,omitempty"`
}

// LegalAddressDto mirrors the iiko DTO of the same name.
type LegalAddressDto struct {
	ZipCode   string `xml:"zipCode,omitempty"`
	Office    string `xml:"office,omitempty"`
	Building  string `xml:"building,omitempty"`
	House     string `xml:"house,omitempty"`
	Street    string `xml:"street,omitempty"`
	Community string `xml:"community,omitempty"`
	City      string `xml:"city,omitempty"`
	District  string `xml:"district,omitempty"`
	Region    string `xml:"region,omitempty"`
	Country   string `xml:"country,omitempty"`
}

// OfficialEmployeeDtoOfficialEmployeeRoleDtoValues are the documented values of OfficialEmployeeDto.OfficialEmployeeRoleDto.
var OfficialEmployeeDtoOfficialEmployeeRoleDtoValues = []string{
	"ACCOUNTANT",
	"LEADER",
	"TECHNOLOGIST",
	"WORKS_MANAGER",
}

// OfficialEmployeeDto mirrors the iiko DTO of the same name.
type OfficialEmployeeDto struct {
	Role string `xml:"role,omitempty"`
	Name string `xml:"name,omitempty"`
}

// PointOfSaleDto mirrors the iiko DTO of the same name.
type PointOfSaleDto struct {
	ID               string    `xml:"id"` // read-only
	Name             string    `xml:"name"`
	Main             bool      `xml:"main"`                       // read-only
	CashRegisterInfo IdNameDto `xml:"cashRegisterInfo,omitempty"` // read-only
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported PointOfSaleDto: encoding/xml cannot skip them per field.
func (x *PointOfSaleDto) StripReadOnly() {
	var zeroID string
	x.ID = zeroID
	var zeroMain bool
	x.Main = zeroMain
	var zeroCashRegisterInfo IdNameDto
	x.CashRegisterInfo = zeroCashRegisterInfo
}

// TerminalDto mirrors the iiko DTO of the same name.
type TerminalDto struct {
	ID                   string    `xml:"id"` // read-only
	Name                 string    `xml:"name"`
	ComputerName         string    `xml:"computerName,omitempty"` // read-only
	Anonymous            bool      `xml:"anonymous"`              // read-only
	GroupInfo            IdNameDto `xml:"groupInfo,omitempty"`    // read-only
	RestaurantSectionIds []string  `xml:"restaurantSectionIds"`   // read-only
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported TerminalDto: encoding/xml cannot skip them per field.
func (x *TerminalDto) StripReadOnly() {
	var zeroID string
	x.ID = zeroID
	var zeroComputerName string
	x.ComputerName = zeroComputerName
	var zeroAnonymous bool
	x.Anonymous = zeroAnonymous
	var zeroGroupInfo IdNameDto
	x.GroupInfo = zeroGroupInfo
	var zeroRestaurantSectionIds []string
	x.RestaurantSectionIds = zeroRestaurantSectionIds
}
