// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package cashshifts

import (
	"encoding/json"
	"reflect"
)

// AddPayOutResultDto mirrors the iiko DTO of the same name.
type AddPayOutResultDto struct {
	Result         string           `json:"result,omitempty"`         // read-only; SUCCESS ERROR
	PayOutSettings PayOutRequestDto `json:"payOutSettings,omitempty"` // read-only; also spelled payOutSettingsDto
	Errors         []ErrorDto       `json:"errors,omitempty"`         // read-only
}

// UnmarshalJSON accepts every documented spelling of AddPayOutResultDto's ambiguous fields.
func (x *AddPayOutResultDto) UnmarshalJSON(data []byte) error {
	type plain AddPayOutResultDto
	var v struct {
		plain
		Alias0_0 PayOutRequestDto `json:"payOutSettingsDto"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = AddPayOutResultDto(v.plain)
	if reflect.DeepEqual(x.PayOutSettings, PayOutRequestDto{}) {
		x.PayOutSettings = v.Alias0_0
	}
	return nil
}

// AuthInfoDto mirrors the iiko DTO of the same name.
type AuthInfoDto struct {
	User string `json:"user,omitempty"` // read-only
	Card string `json:"card,omitempty"` // read-only
}

// CashFlowCategoryDto mirrors the iiko DTO of the same name.
type CashFlowCategoryDto struct {
	ID               string `json:"id,omitempty"`               // read-only
	Code             string `json:"code,omitempty"`             // read-only
	ParentCategoryID string `json:"parentCategoryId,omitempty"` // read-only; also spelled parentCategory
	Type             string `json:"type,omitempty"`             // read-only; OPERATIONAL INVESTMENT FINANCE
}

// UnmarshalJSON accepts every documented spelling of CashFlowCategoryDto's ambiguous fields.
func (x *CashFlowCategoryDto) UnmarshalJSON(data []byte) error {
	type plain CashFlowCategoryDto
	var v struct {
		plain
		Alias0_0 string `json:"parentCategory"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = CashFlowCategoryDto(v.plain)
	if x.ParentCategoryID == "" {
		x.ParentCategoryID = v.Alias0_0
	}
	return nil
}

// CashShiftPaymentsDto mirrors the iiko DTO of the same name.
type CashShiftPaymentsDto struct {
	SessionID       string             `json:"sessionId,omitempty"`       // read-only
	OperationDay    string             `json:"operationDay,omitempty"`    // read-only
	CashlessRecords []PaymentRecordDto `json:"cashlessRecords,omitempty"` // read-only
	PayInRecords    []PaymentRecordDto `json:"payInRecords,omitempty"`    // read-only
	PayOutRecords   []PaymentRecordDto `json:"payOutRecords,omitempty"`   // read-only; also spelled payOutsRecords
}

// UnmarshalJSON accepts every documented spelling of CashShiftPaymentsDto's ambiguous fields.
func (x *CashShiftPaymentsDto) UnmarshalJSON(data []byte) error {
	type plain CashShiftPaymentsDto
	var v struct {
		plain
		Alias0_0 []PaymentRecordDto `json:"payOutsRecords"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = CashShiftPaymentsDto(v.plain)
	if len(x.PayOutRecords) == 0 {
		x.PayOutRecords = v.Alias0_0
	}
	return nil
}

// CashShiftSessionDto mirrors the iiko DTO of the same name.
type CashShiftSessionDto struct {
	ID                string  `json:"id,omitempty"`                // read-only
	SessionNumber     int     `json:"sessionNumber,omitempty"`     // read-only
	FiscalNumber      int     `json:"fiscalNumber,omitempty"`      // read-only
	CashRegNumber     int     `json:"cashRegNumber,omitempty"`     // read-only
	CashRegSerial     string  `json:"cashRegSerial,omitempty"`     // read-only
	OpenDate          string  `json:"openDate,omitempty"`          // read-only
	CloseDate         string  `json:"closeDate,omitempty"`         // read-only
	AcceptDate        string  `json:"acceptDate,omitempty"`        // read-only
	ManagerID         string  `json:"managerId,omitempty"`         // read-only; also spelled manager
	ResponsibleUser   string  `json:"responsibleUser,omitempty"`   // read-only
	SessionStartCash  float64 `json:"sessionStartCash,omitempty"`  // read-only
	PayOrders         float64 `json:"payOrders,omitempty"`         // read-only
	SumWriteoffOrders float64 `json:"sumWriteoffOrders,omitempty"` // read-only
	SalesCash         float64 `json:"salesCash,omitempty"`         // read-only
	SalesCredit       float64 `json:"salesCredit,omitempty"`       // read-only; also spelled salesCerdit
	SalesCard         float64 `json:"salesCard,omitempty"`         // read-only
	PayIn             float64 `json:"payIn,omitempty"`             // read-only
	PayOut            float64 `json:"payOut,omitempty"`            // read-only
	PayIncome         float64 `json:"payIncome,omitempty"`         // read-only
	CashRemain        float64 `json:"cashRemain,omitempty"`        // read-only
	CashDiff          float64 `json:"cashDiff,omitempty"`          // read-only
	SessionStatus     string  `json:"sessionStatus,omitempty"`     // read-only; OPEN CLOSED ACCEPTED UNACCEPTED HASWARNINGS; also spelled sessionStaus
	Conception        string  `json:"conception,omitempty"`        // read-only
	PointOfSale       string  `json:"pointOfSale,omitempty"`       // read-only
}

// UnmarshalJSON accepts every documented spelling of CashShiftSessionDto's ambiguous fields.
func (x *CashShiftSessionDto) UnmarshalJSON(data []byte) error {
	type plain CashShiftSessionDto
	var v struct {
		plain
		Alias0_0 string  `json:"manager"`
		Alias1_0 float64 `json:"salesCerdit"`
		Alias2_0 string  `json:"sessionStaus"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = CashShiftSessionDto(v.plain)
	if x.ManagerID == "" {
		x.ManagerID = v.Alias0_0
	}
	if x.SalesCredit == 0 {
		x.SalesCredit = v.Alias1_0
	}
	if x.SessionStatus == "" {
		x.SessionStatus = v.Alias2_0
	}
	return nil
}

// ClosedSessionDocumentDto mirrors the iiko DTO of the same name.
type ClosedSessionDocumentDto struct {
	ID                     string                 `json:"id,omitempty"`
	Session                SessionRefDto          `json:"session,omitempty"`
	AccountShortageID      string                 `json:"accountShortageId,omitempty"`
	CounteragentShortageID string                 `json:"counteragentShortageId,omitempty"`
	AccountSurplusID       string                 `json:"accountSurplusId,omitempty"`
	CounteragentSurplusID  string                 `json:"counteragentSurplusId,omitempty"`
	DepartmentID           string                 `json:"departmentId,omitempty"`
	Items                  []ClosedSessionItemDto `json:"items,omitempty"`
}

// ClosedSessionItemDtoAccountTypeValues are the documented values of ClosedSessionItemDto.AccountType.
var ClosedSessionItemDtoAccountTypeValues = []string{
	"ACCOUNTS_RECEIVABLE",
	"DEBTS_OF_EMPLOYEES",
	"EMPLOYEES_LIABILITY",
	"ACCOUNTS_PAYABLE",
	"CLIENTS_LIABILITY",
}

// ClosedSessionItemDto mirrors the iiko DTO of the same name.
type ClosedSessionItemDto struct {
	Num                    int     `json:"num,omitempty"`
	TransactionID          string  `json:"transactionId,omitempty"`
	SumReal                float64 `json:"sumReal,omitempty"`
	AccountOverrideID      string  `json:"accountOverrideId,omitempty"`
	CounteragentOverrideID string  `json:"counteragentOverrideId,omitempty"`
	Status                 string  `json:"status,omitempty"` // ACCEPTED UNACCEPTED HASWARNINGS
	Comment                string  `json:"comment,omitempty"`
}

// ConceptionRefDto mirrors the iiko DTO of the same name.
type ConceptionRefDto struct {
	ID   string `json:"id,omitempty"`   // read-only
	Code string `json:"code,omitempty"` // read-only
	Name string `json:"name,omitempty"` // read-only
}

// ErrorDto mirrors the iiko DTO of the same name.
type ErrorDto struct {
	Value string `json:"value,omitempty"` // read-only
	Code  string `json:"code,omitempty"`  // read-only; ACCOUNT_DELETED COUNTERAGENT_DELETED INVENTORY_ASSETS_TYPE_NOT_ALLOWED COUNTERAGENT_MISSED_FOR_ACCOUNT COUNTERAGENT_NOT_ALLOWED_FOR_ACCOUNT ACCOUNT_NOT_SPECIFIED COUNTERAGENT_NOT_SPECIFIED COUNTERAGENT_NOT_ALLOWED COUNTERAGENT_TYPE_WRONG CONCEPTION_NOT_SPECIFIED CONCEPTION_DELETED PAYROLL_MISSED_FOR_ACCOUNT PAYROLL_DELETED ONLY_POSITIVE_VALUES_ALLOWED DEPARTMENT_DELETED RESTAURANT_SECTION_DELETED MEASURE_UNIT_DELETED COOKING_PLACE_DELETED TAX_CATEGORY_DELETED PRODUCT_CATEGORY_DELETED PRODUCT_GROUP_DELETED PRODUCT_DELETED PRODUCT_MISSED COOKING_PLACE_EMPTY_FOR_SALE_DISH WRONG_NOMENCLATURE_TYPE NOT_INCLUDED_IN_MENU_WITH_EXCLUDED_SECTIONS CHILD_MODIFIERS_NOT_ALLOWED MODIFIER_NOT_BELONGS_TO_GROUP NOT_MODIFIER WRONG_MIN_MAX_AMOUNT HAS_RESTRICTION_AND_DEFAULT_AMOUNT_OUT_OF_RANGE DEFAULT_AMOUNT_OUT_OF_RANGE NO_RESTRICTION_AND_MIN_MAX_NOT_ZERO REQUIRED_AND_WRONG_MIN_AMOUNT FREE_OF_CHARGE_AMOUNT_MORE_THAN_MAX HAS_RESTRICTION_AND_FREE_OF_CHARGE_MORE_THAN_MAX HAS_RESTRICTION_AND_FREE_OF_CHARGE_MORE_THAN_PARENT NO_RESTRICTION_AND_FREE_OF_CHARGE_AMOUNT_NOT_EQUAL_VALUE_IN_PARENT NO_RESTRICTION_AND_REQUIRED_SHOULD_BE_FALSE NOT_GROUP_MODIFIER_HAS_CHILD_RESTRICTION SINGLE_MODIFIER_HIDE_DEFAULT_AMOUNT PARENT_AMOUNT_BY_DEFAULT_NOT_EQUAL_SUM_OF_CHILDREN IMAGE_NOT_FOUND
}

// ItemErrorDto mirrors the iiko DTO of the same name.
type ItemErrorDto struct {
	Identifier int        `json:"identifier,omitempty"` // read-only
	Error      []ErrorDto `json:"error,omitempty"`      // read-only
}

// PayInOutTypeDto mirrors the iiko DTO of the same name.
type PayInOutTypeDto struct {
	ID                    string              `json:"id,omitempty"`                    // read-only
	ChiefAccount          string              `json:"chiefAccount,omitempty"`          // read-only
	Account               string              `json:"account,omitempty"`               // read-only
	CounteragentType      string              `json:"counteragentType,omitempty"`      // read-only; NONE COUNTERAGENT EMPLOYEE SUPPLIER CLIENT INTERNAL_SUPPLIER
	TransactionType       string              `json:"transactionType,omitempty"`       // read-only; PAYIN PAYOUT
	CashFlowCategory      CashFlowCategoryDto `json:"cashFlowCategory,omitempty"`      // read-only
	Conception            ConceptionRefDto    `json:"conception,omitempty"`            // read-only
	Limit                 float64             `json:"limit,omitempty"`                 // read-only
	Comment               string              `json:"comment,omitempty"`               // read-only
	MandatoryFrontComment bool                `json:"mandatoryFrontComment,omitempty"` // read-only
	IsDeleted             bool                `json:"isDeleted,omitempty"`             // read-only
}

// PayOutRequestDto mirrors the iiko DTO of the same name.
type PayOutRequestDto struct {
	PayOutTypeID     string          `json:"payOutTypeId"`
	PayOutDate       string          `json:"payOutDate"`
	Counteragent     string          `json:"counteragent,omitempty"`
	DepartmentSumMap json.RawMessage `json:"departmentSumMap"`
	PayrollID        string          `json:"payrollId,omitempty"`
	Comment          string          `json:"comment,omitempty"`
}

// PaymentRecordDto mirrors the iiko DTO of the same name.
type PaymentRecordDto struct {
	Info                 TransactionInfoDto `json:"info,omitempty"`                 // read-only
	ActualSum            float64            `json:"actualSum,omitempty"`            // read-only
	OriginalSum          float64            `json:"originalSum,omitempty"`          // read-only
	EditedPayAccountID   string             `json:"editedPayAccountId,omitempty"`   // read-only
	OriginalPayAccountID string             `json:"originalPayAccountId,omitempty"` // read-only
	PayAgentID           string             `json:"payAgentId,omitempty"`           // read-only
	PaymentTypeID        string             `json:"paymentTypeId,omitempty"`        // read-only
	EditableComment      string             `json:"editableComment,omitempty"`
	Status               string             `json:"status,omitempty"` // ACCEPTED UNACCEPTED HASWARNINGS
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x PaymentRecordDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		EditableComment string `json:"editableComment,omitempty"`
		Status          string `json:"status,omitempty"`
	}{
		EditableComment: x.EditableComment,
		Status:          x.Status,
	})
}

// PayrollDtoDocumentStatusValues are the documented values of PayrollDto.DocumentStatus.
var PayrollDtoDocumentStatusValues = []string{
	"NEW",
	"PROCESSED",
	"DELETED",
}

// PayrollDto mirrors the iiko DTO of the same name.
type PayrollDto struct {
	ID             string `json:"id,omitempty"`             // read-only; also spelled payrollId
	DateFrom       string `json:"dateFrom,omitempty"`       // read-only
	DateTo         string `json:"dateTo,omitempty"`         // read-only
	Department     string `json:"department,omitempty"`     // read-only
	DocumentNumber string `json:"documentNumber,omitempty"` // read-only
	Status         string `json:"status,omitempty"`         // read-only; NEW PROCESSED DELETED
	Comment        string `json:"comment,omitempty"`        // read-only
}

// UnmarshalJSON accepts every documented spelling of PayrollDto's ambiguous fields.
func (x *PayrollDto) UnmarshalJSON(data []byte) error {
	type plain PayrollDto
	var v struct {
		plain
		Alias0_0 string `json:"payrollId"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = PayrollDto(v.plain)
	if x.ID == "" {
		x.ID = v.Alias0_0
	}
	return nil
}

// SaveErrorsDto mirrors the iiko DTO of the same name.
type SaveErrorsDto struct {
	DocumentError []ErrorDto     `json:"documentError,omitempty"` // read-only
	ItemError     []ItemErrorDto `json:"itemError,omitempty"`     // read-only
}

// SaveResultDto mirrors the iiko DTO of the same name.
type SaveResultDto struct {
	ImportResult string                   `json:"importResult,omitempty"` // read-only; SUCCESS ERROR
	Status       string                   `json:"status,omitempty"`       // read-only; UNACCEPTED ACCEPTED HASWARNINGS
	Errors       SaveErrorsDto            `json:"errors,omitempty"`       // read-only
	Document     ClosedSessionDocumentDto `json:"document,omitempty"`     // read-only
}

// SessionRefDto mirrors the iiko DTO of the same name.
type SessionRefDto struct {
	SessionID string `json:"sessionId,omitempty"`
	GroupID   string `json:"groupId,omitempty"` // also spelled group
	Number    int    `json:"number,omitempty"`
}

// UnmarshalJSON accepts every documented spelling of SessionRefDto's ambiguous fields.
func (x *SessionRefDto) UnmarshalJSON(data []byte) error {
	type plain SessionRefDto
	var v struct {
		plain
		Alias0_0 string `json:"group"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = SessionRefDto(v.plain)
	if x.GroupID == "" {
		x.GroupID = v.Alias0_0
	}
	return nil
}

// TransactionInfoDto mirrors the iiko DTO of the same name.
type TransactionInfoDto struct {
	ID               string              `json:"id,omitempty"`               // read-only
	Date             string              `json:"date,omitempty"`             // read-only
	CreationDate     string              `json:"creationDate,omitempty"`     // read-only
	Group            string              `json:"group,omitempty"`            // read-only; CARD CREDIT PAYOUT PAYIN
	AccountID        string              `json:"accountId,omitempty"`        // read-only
	CounteragentID   string              `json:"counteragentId,omitempty"`   // read-only
	PaymentTypeID    string              `json:"paymentTypeId,omitempty"`    // read-only
	Type             string              `json:"type,omitempty"`             // read-only
	Sum              float64             `json:"sum,omitempty"`              // read-only
	Comment          string              `json:"comment,omitempty"`          // read-only
	Auth             AuthInfoDto         `json:"auth,omitempty"`             // read-only
	CauseEventID     string              `json:"causeEventId,omitempty"`     // read-only; also spelled causeEvenId
	CashierID        string              `json:"cashierId,omitempty"`        // read-only
	DepartmentID     string              `json:"departmentId,omitempty"`     // read-only
	CashFlowCategory CashFlowCategoryDto `json:"cashFlowCategory,omitempty"` // read-only
}

// UnmarshalJSON accepts every documented spelling of TransactionInfoDto's ambiguous fields.
func (x *TransactionInfoDto) UnmarshalJSON(data []byte) error {
	type plain TransactionInfoDto
	var v struct {
		plain
		Alias0_0 string `json:"causeEvenId"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = TransactionInfoDto(v.plain)
	if x.CauseEventID == "" {
		x.CauseEventID = v.Alias0_0
	}
	return nil
}
