// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package staff

// AssignmentEntryDto mirrors the iiko DTO of the same name.
type AssignmentEntryDto struct {
	EmployeeID string `xml:"employeeId"`
	TeamID     string `xml:"teamId,omitempty"`
}

// AttendanceDto mirrors the iiko DTO of the same name.
type AttendanceDto struct {
	ID               string            `xml:"id,omitempty"`
	EmployeeID       string            `xml:"employeeId"`
	RoleID           string            `xml:"roleId,omitempty"`
	AttendanceTypeID string            `xml:"attendanceTypeId,omitempty"`
	AttendanceType   string            `xml:"attendanceType,omitempty"`
	Comment          string            `xml:"comment,omitempty"`
	DateFrom         string            `xml:"dateFrom,omitempty"`
	DateTo           string            `xml:"dateTo,omitempty"`
	PersonalDateFrom string            `xml:"personalDateFrom,omitempty"`
	PersonalDateTo   string            `xml:"personalDateTo,omitempty"`
	DepartmentID     string            `xml:"departmentId"`
	DepartmentName   string            `xml:"departmentName"`
	PaymentDetails   PaymentDetailsDto `xml:"paymentDetails,omitempty"` // read-only
	Created          string            `xml:"created,omitempty"`        // read-only
	Modified         string            `xml:"modified,omitempty"`       // read-only
	UserModified     string            `xml:"userModified,omitempty"`   // read-only
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported AttendanceDto: encoding/xml cannot skip them per field.
func (x *AttendanceDto) StripReadOnly() {
	var zeroPaymentDetails PaymentDetailsDto
	x.PaymentDetails = zeroPaymentDetails
	var zeroCreated string
	x.Created = zeroCreated
	var zeroModified string
	x.Modified = zeroModified
	var zeroUserModified string
	x.UserModified = zeroUserModified
}

// AttendanceTypeDto mirrors the iiko DTO of the same name.
type AttendanceTypeDto struct {
	ID      string  `xml:"id"`
	Code    string  `xml:"code"`
	Name    string  `xml:"name"`
	PayRate float64 `xml:"payRate,omitempty"`
	Status  bool    `xml:"status"`
	Comment float64 `xml:"comment,omitempty"`
}

// AvailabilityDto mirrors the iiko DTO of the same name.
type AvailabilityDto struct {
	EmployeeID string `xml:"employeeId"` // read-only
	DateFrom   string `xml:"dateFrom"`   // read-only
	DateTo     string `xml:"dateTo"`     // read-only
}

// EmployeeDto is Shape reconciled across domains. The docs for /resto/api/suppliers, /resto/api/suppliers/search show only a re…
type EmployeeDto struct {
	ID                            string                       `xml:"id"` // read-only
	Code                          string                       `xml:"code"`
	Name                          string                       `xml:"name"`
	Login                         string                       `xml:"login,omitempty"`
	Password                      string                       `xml:"password,omitempty"`
	MainRoleID                    string                       `xml:"mainRoleId,omitempty"`
	RolesIds                      []string                     `xml:"rolesIds,omitempty"`
	MainRoleCode                  string                       `xml:"mainRoleCode,omitempty"`
	RoleCodes                     []string                     `xml:"roleCodes,omitempty"`
	Phone                         string                       `xml:"phone,omitempty"`
	CellPhone                     string                       `xml:"cellPhone,omitempty"`
	FirstName                     string                       `xml:"firstName,omitempty"`
	MiddleName                    string                       `xml:"middleName,omitempty"`
	LastName                      string                       `xml:"lastName,omitempty"`
	Birthday                      string                       `xml:"birthday,omitempty"`
	Email                         string                       `xml:"email,omitempty"`
	Address                       string                       `xml:"address,omitempty"`
	HireDate                      string                       `xml:"hireDate,omitempty"`
	HireDocumentNumber            string                       `xml:"hireDocumentNumber,omitempty"`
	FireDate                      string                       `xml:"fireDate,omitempty"`
	Note                          string                       `xml:"note,omitempty"`
	CardNumber                    string                       `xml:"cardNumber,omitempty"`
	PinCode                       string                       `xml:"pinCode,omitempty"`
	TaxpayerIDNumber              string                       `xml:"taxpayerIdNumber,omitempty"`
	Snils                         string                       `xml:"snils,omitempty"`
	GLN                           string                       `xml:"gln,omitempty"`
	ActivationDate                string                       `xml:"activationDate,omitempty"`
	DeactivationDate              string                       `xml:"deactivationDate,omitempty"`
	PreferredDepartmentCode       string                       `xml:"preferredDepartmentCode,omitempty"`
	DepartmentCodes               []string                     `xml:"departmentCodes,omitempty"`
	ResponsibilityDepartmentCodes []string                     `xml:"responsibilityDepartmentCodes,omitempty"`
	Deleted                       bool                         `xml:"deleted,omitempty"`
	Supplier                      bool                         `xml:"supplier,omitempty"`
	Employee                      bool                         `xml:"employee,omitempty"`
	Client                        bool                         `xml:"client,omitempty"`
	PublicExternalData            []PublicExternalDataEntryDto `xml:"publicExternalData"`
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported EmployeeDto: encoding/xml cannot skip them per field.
func (x *EmployeeDto) StripReadOnly() {
	var zeroID string
	x.ID = zeroID
}

// EmployeeRoleDtoPaymentSchemeValues are the documented values of EmployeeRoleDto.paymentScheme.
var EmployeeRoleDtoPaymentSchemeValues = []string{
	"SESSION",
	"HOURS",
	"FIXED",
}

// EmployeeRoleDto mirrors the iiko DTO of the same name.
type EmployeeRoleDto struct {
	ID             string  `xml:"id"`
	Code           string  `xml:"code"`
	Name           string  `xml:"name"`
	PaymentPerHour float64 `xml:"paymentPerHour,omitempty"`
	SteadySalary   float64 `xml:"steadySalary,omitempty"` // read-only
	ScheduleType   string  `xml:"scheduleType,omitempty"` // SESSION HOURS FIXED
	Deleted        bool    `xml:"deleted,omitempty"`
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported EmployeeRoleDto: encoding/xml cannot skip them per field.
func (x *EmployeeRoleDto) StripReadOnly() {
	var zeroSteadySalary float64
	x.SteadySalary = zeroSteadySalary
}

// PaymentDetailsDto mirrors the iiko DTO of the same name.
type PaymentDetailsDto struct {
	SalaryDepartmentID   string  `xml:"salaryDepartmentId"`   // read-only
	SalaryDepartmentName string  `xml:"salaryDepartmentName"` // read-only
	RegularPayedMinutes  int     `xml:"regularPayedMinutes"`  // read-only
	RegularPaymentSum    float64 `xml:"regularPaymentSum"`    // read-only
	OvertimePayedMinutes int     `xml:"overtimePayedMinutes"` // read-only
	OvertimePaymentSum   float64 `xml:"overtimePaymentSum"`   // read-only; also spelled overtimePayedSum
	OtherPaymentsSum     float64 `xml:"otherPaymentsSum"`     // read-only
}

// PublicExternalDataEntryDto mirrors the iiko DTO of the same name.
type PublicExternalDataEntryDto struct {
	Key   string `xml:"key"`
	Value string `xml:"value,omitempty"`
}

// SalaryDto mirrors the iiko DTO of the same name.
type SalaryDto struct {
	DateFrom   string  `xml:"dateFrom,omitempty"`
	DateTo     string  `xml:"dateTo,omitempty"`
	EmployeeID string  `xml:"employeeId,omitempty"`
	Payment    float64 `xml:"payment,omitempty"`
}

// ScheduleDto mirrors the iiko DTO of the same name.
type ScheduleDto struct {
	ID               string            `xml:"id,omitempty"`
	EmployeeID       string            `xml:"employeeId"`
	RoleID           string            `xml:"roleId,omitempty"`
	NonPaidMinutes   int               `xml:"nonPaidMinutes,omitempty"`
	ScheduleTypeID   string            `xml:"scheduleTypeId,omitempty"`
	ScheduleTypeCode string            `xml:"scheduleTypeCode,omitempty"`
	DateFrom         string            `xml:"dateFrom,omitempty"`
	DateTo           string            `xml:"dateTo,omitempty"`
	DepartmentID     string            `xml:"departmentId"`
	DepartmentName   string            `xml:"departmentName"`
	PaymentDetails   PaymentDetailsDto `xml:"paymentDetails,omitempty"` // read-only
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported ScheduleDto: encoding/xml cannot skip them per field.
func (x *ScheduleDto) StripReadOnly() {
	var zeroPaymentDetails PaymentDetailsDto
	x.PaymentDetails = zeroPaymentDetails
}

// ScheduleTypeDto mirrors the iiko DTO of the same name.
type ScheduleTypeDto struct {
	ID            string  `xml:"id"`
	Code          string  `xml:"code"`
	Name          string  `xml:"name"`
	LengthMinutes int     `xml:"lengthMinutes"`
	StartTime     string  `xml:"startTime"`
	Overtime      bool    `xml:"overtime"`
	Tariff        float64 `xml:"tariff,omitempty"`
	Comment       float64 `xml:"comment,omitempty"`
}

// WaiterTeamAssignmentsDto mirrors the iiko DTO of the same name.
type WaiterTeamAssignmentsDto struct {
	ID           string               `xml:"id,omitempty"` // read-only
	Assignment   []AssignmentEntryDto `xml:"assignment,omitempty"`
	DepartmentID string               `xml:"departmentId,omitempty"`
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported WaiterTeamAssignmentsDto: encoding/xml cannot skip them per field.
func (x *WaiterTeamAssignmentsDto) StripReadOnly() {
	var zeroID string
	x.ID = zeroID
}

// WaiterTeamDto mirrors the iiko DTO of the same name.
type WaiterTeamDto struct {
	ID           string `xml:"id,omitempty"`
	Code         string `xml:"code,omitempty"`
	Name         string `xml:"name"`
	Deleted      bool   `xml:"deleted,omitempty"`
	DepartmentID string `xml:"departmentId,omitempty"`
}
