// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package recipes

import (
	"encoding/json"
)

// AssemblyChartItemDto mirrors the iiko DTO of the same name.
type AssemblyChartItemDto struct {
	ID                       string          `json:"id,omitempty"` // read-only
	SortWeight               float64         `json:"sortWeight,omitempty"`
	ProductID                string          `json:"productId,omitempty"`
	ProductSizeSpecification string          `json:"productSizeSpecification,omitempty"`
	StoreSpecification       json.RawMessage `json:"storeSpecification,omitempty"`
	AmountIn                 float64         `json:"amountIn,omitempty"`
	AmountMiddle             float64         `json:"amountMiddle,omitempty"`
	AmountOut                float64         `json:"amountOut,omitempty"`
	AmountIn1                float64         `json:"amountIn1,omitempty"`
	AmountOut1               float64         `json:"amountOut1,omitempty"`
	AmountIn2                float64         `json:"amountIn2,omitempty"`
	AmountOut2               float64         `json:"amountOut2,omitempty"`
	AmountIn3                float64         `json:"amountIn3,omitempty"`
	AmountOut3               float64         `json:"amountOut3,omitempty"`
	PackageCount             float64         `json:"packageCount,omitempty"`
	PackageTypeID            string          `json:"packageTypeId,omitempty"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x AssemblyChartItemDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		SortWeight               float64         `json:"sortWeight,omitempty"`
		ProductID                string          `json:"productId,omitempty"`
		ProductSizeSpecification string          `json:"productSizeSpecification,omitempty"`
		StoreSpecification       json.RawMessage `json:"storeSpecification,omitempty"`
		AmountIn                 float64         `json:"amountIn,omitempty"`
		AmountMiddle             float64         `json:"amountMiddle,omitempty"`
		AmountOut                float64         `json:"amountOut,omitempty"`
		AmountIn1                float64         `json:"amountIn1,omitempty"`
		AmountOut1               float64         `json:"amountOut1,omitempty"`
		AmountIn2                float64         `json:"amountIn2,omitempty"`
		AmountOut2               float64         `json:"amountOut2,omitempty"`
		AmountIn3                float64         `json:"amountIn3,omitempty"`
		AmountOut3               float64         `json:"amountOut3,omitempty"`
		PackageCount             float64         `json:"packageCount,omitempty"`
		PackageTypeID            string          `json:"packageTypeId,omitempty"`
	}{
		SortWeight:               x.SortWeight,
		ProductID:                x.ProductID,
		ProductSizeSpecification: x.ProductSizeSpecification,
		StoreSpecification:       x.StoreSpecification,
		AmountIn:                 x.AmountIn,
		AmountMiddle:             x.AmountMiddle,
		AmountOut:                x.AmountOut,
		AmountIn1:                x.AmountIn1,
		AmountOut1:               x.AmountOut1,
		AmountIn2:                x.AmountIn2,
		AmountOut2:               x.AmountOut2,
		AmountIn3:                x.AmountIn3,
		AmountOut3:               x.AmountOut3,
		PackageCount:             x.PackageCount,
		PackageTypeID:            x.PackageTypeID,
	})
}

// PreparedChartItemDto mirrors the iiko DTO of the same name.
type PreparedChartItemDto struct {
	ID                       string          `json:"id,omitempty"` // read-only
	SortWeight               float64         `json:"sortWeight,omitempty"`
	ProductID                string          `json:"productId,omitempty"`
	ProductSizeSpecification string          `json:"productSizeSpecification,omitempty"`
	StoreSpecification       json.RawMessage `json:"storeSpecification,omitempty"`
	Amount                   float64         `json:"amount,omitempty"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x PreparedChartItemDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		SortWeight               float64         `json:"sortWeight,omitempty"`
		ProductID                string          `json:"productId,omitempty"`
		ProductSizeSpecification string          `json:"productSizeSpecification,omitempty"`
		StoreSpecification       json.RawMessage `json:"storeSpecification,omitempty"`
		Amount                   float64         `json:"amount,omitempty"`
	}{
		SortWeight:               x.SortWeight,
		ProductID:                x.ProductID,
		ProductSizeSpecification: x.ProductSizeSpecification,
		StoreSpecification:       x.StoreSpecification,
		Amount:                   x.Amount,
	})
}
