// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package edi

// ContainerDto__edi is NAME COLLISION: the docs use the name "ContainerDto" for structurally unrelated types in different domains. Re…
type ContainerDto__edi struct {
	InternalCode string  `xml:"internalCode,omitempty"`
	Name         string  `xml:"name,omitempty"`
	Quantity     float64 `xml:"quantity"`
}

// ContractorDto mirrors the iiko DTO of the same name.
type ContractorDto struct {
	GLN          string `xml:"gln,omitempty"`
	Guid         string `xml:"guid,omitempty"`
	Name         string `xml:"name,omitempty"`
	InternalCode string `xml:"internalCode,omitempty"`
	INN          string `xml:"inn,omitempty"`
	KPP          string `xml:"kpp,omitempty"`
}

// DeliveryInfoDto mirrors the iiko DTO of the same name.
type DeliveryInfoDto struct {
	RequestedDeliveryDateTime string `xml:"requestedDeliveryDateTime,omitempty"`
	EstimatedDeliveryDateTime string `xml:"estimatedDeliveryDateTime,omitempty"`
}

// DocumentIdentifierDto mirrors the iiko DTO of the same name.
type DocumentIdentifierDto struct {
	Number string `xml:"number,attr"`
	Date   string `xml:"date,attr"`
	Type   string `xml:"type,attr,omitempty"`
}

// EdiMessageDto mirrors the iiko DTO of the same name.
type EdiMessageDto struct {
	ID               string              `xml:"id,attr"`
	CreationDateTime string              `xml:"creationDateTime,attr,omitempty"`
	Header           EdiMessageHeaderDto `xml:"header"`
	Order            OrderDto            `xml:"order,omitempty"`
	Ordersp          OrderResponseDto    `xml:"ordersp,omitempty"`
	Invoice          InvoiceDto          `xml:"invoice,omitempty"`
}

// EdiMessageHeaderDtoDocumentTypeDtoValues are the documented values of EdiMessageHeaderDto.DocumentTypeDto.
var EdiMessageHeaderDtoDocumentTypeDtoValues = []string{
	"ORDERS",
	"ORDRSP",
	"INVOIC",
}

// EdiMessageHeaderDto mirrors the iiko DTO of the same name.
type EdiMessageHeaderDto struct {
	Sender       ContractorDto `xml:"sender"`
	Recipient    ContractorDto `xml:"recipient"`
	DocumentType string        `xml:"documentType"` // ORDERS ORDRSP INVOIC
}

// EdiOrderWarningDtoEdiCreateWarningCodeValues are the documented values of EdiOrderWarningDto.EdiCreateWarningCode.
var EdiOrderWarningDtoEdiCreateWarningCodeValues = []string{
	"SUPPLIER_PRODUCT_NOT_FOUND",
	"SUPPLIER_PRICELIST_NOT_FOUND",
	"PRODUCT_AND_SUPPLIER_PRODUCT_DO_NOT_MATCH",
	"ORDER_ITEM_IS_POSSIBLY_INCORRECT",
}

// EdiOrderWarningDto mirrors the iiko DTO of the same name.
type EdiOrderWarningDto struct {
	Code    string `xml:"code,attr"` // read-only; SUPPLIER_PRODUCT_NOT_FOUND SUPPLIER_PRICELIST_NOT_FOUND PRODUCT_AND_SUPPLIER_PRODUCT_DO_NOT_MATCH ORDER_ITEM_IS_POSSIBLY_INCORRECT
	Message string `xml:",chardata"` // read-only
}

// InvoiceDto mirrors the iiko DTO of the same name.
type InvoiceDto struct {
	Number                 string                `xml:"number,attr"`
	Date                   string                `xml:"date,attr"`
	Type                   string                `xml:"type,attr"`
	OriginOrder            DocumentIdentifierDto `xml:"originOrder"`
	Seller                 ContractorDto         `xml:"seller,omitempty"`
	Buyer                  ContractorDto         `xml:"buyer,omitempty"`
	Invoicee               ContractorDto         `xml:"invoicee,omitempty"`
	DeliveryInfo           DeliveryInfoDto       `xml:"deliveryInfo"`
	LineItems              []InvoiceItemDto      `xml:"lineItems>lineItem"`
	TotalSumExcludingTaxes float64               `xml:"totalSumExcludingTaxes,omitempty"`
	TotalVATSum            float64               `xml:"totalVATSum,omitempty"`
	TotalSum               float64               `xml:"totalSum,omitempty"`
}

// InvoiceItemDto mirrors the iiko DTO of the same name.
type InvoiceItemDto struct {
	Gtin                 string      `xml:"gtin,omitempty"`
	InternalBuyerCode    string      `xml:"internalBuyerCode,omitempty"`
	InternalSupplierCode string      `xml:"internalSupplierCode,omitempty"`
	OrderLineNumber      int         `xml:"orderLineNumber"`
	LineNumber           int         `xml:"lineNumber"`
	Name                 string      `xml:"name,omitempty"`
	Comment              string      `xml:"comment,omitempty"`
	RequestedQuantity    QuantityDto `xml:"requestedQuantity,omitempty"`
	ConfirmedQuantity    QuantityDto `xml:"confirmedQuantity"`
	PriceWithVAT         float64     `xml:"priceWithVat,omitempty"`
	SumWithVAT           float64     `xml:"sumWithVat"`
}

// OrderCreationOrUpdateResultDto mirrors the iiko DTO of the same name.
type OrderCreationOrUpdateResultDto struct {
	Warnings []EdiOrderWarningDto `xml:"warnings>warning"` // read-only
	Order    OrderDto             `xml:"order"`            // read-only
}

// OrderDtoOrderStatusDtoValues are the documented values of OrderDto.OrderStatusDto.
var OrderDtoOrderStatusDtoValues = []string{
	"original",
	"canceled",
}

// OrderDto mirrors the iiko DTO of the same name.
type OrderDto struct {
	Number           string          `xml:"number,attr"`
	Date             string          `xml:"date,attr"`
	Status           string          `xml:"status,attr"`                     // original canceled
	ProcessingStatus string          `xml:"processingStatus,attr,omitempty"` // read-only; draft readyToSend registered
	Seller           ContractorDto   `xml:"seller"`
	Buyer            ContractorDto   `xml:"buyer"`
	Invoicee         ContractorDto   `xml:"invoicee,omitempty"`
	DeliveryInfo     DeliveryInfoDto `xml:"deliveryInfo"`
	Comment          string          `xml:"comment,omitempty"`
	LineItems        []OrderItemDto  `xml:"lineItems>lineItem"`
	TotalSumWithVAT  float64         `xml:"totalSumWithVat,omitempty"`
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported OrderDto: encoding/xml cannot skip them per field.
func (x *OrderDto) StripReadOnly() {
	var zeroProcessingStatus string
	x.ProcessingStatus = zeroProcessingStatus
}

// OrderItemDto mirrors the iiko DTO of the same name.
type OrderItemDto struct {
	LineNumber           int         `xml:"lineNumber"`
	Gtin                 string      `xml:"gtin,omitempty"`
	InternalBuyerCode    string      `xml:"internalBuyerCode,omitempty"`
	InternalSupplierCode string      `xml:"internalSupplierCode,omitempty"`
	Name                 string      `xml:"name,omitempty"`
	Comment              string      `xml:"comment,omitempty"`
	RequestedQuantity    QuantityDto `xml:"requestedQuantity"`
	PriceWithVAT         float64     `xml:"priceWithVat,omitempty"`
	SumWithVAT           float64     `xml:"sumWithVat"`
}

// OrderResponseDtoOrderResponseStatusDtoValues are the documented values of OrderResponseDto.OrderResponseStatusDto.
var OrderResponseDtoOrderResponseStatusDtoValues = []string{
	"Rejected",
	"Accepted",
}

// OrderResponseDto mirrors the iiko DTO of the same name.
type OrderResponseDto struct {
	Number                 string                 `xml:"number,attr"`
	Date                   string                 `xml:"date,attr"`
	Status                 string                 `xml:"status,attr"` // Rejected Accepted
	OriginOrder            DocumentIdentifierDto  `xml:"originOrder"`
	Seller                 ContractorDto          `xml:"seller,omitempty"`
	Buyer                  ContractorDto          `xml:"buyer,omitempty"`
	Invoicee               ContractorDto          `xml:"invoicee,omitempty"`
	DeliveryInfo           DeliveryInfoDto        `xml:"deliveryInfo,omitempty"`
	LineItems              []OrderResponseItemDto `xml:"lineItems>lineItem"`
	TotalSumExcludingTaxes float64                `xml:"totalSumExcludingTaxes,omitempty"`
	TotalVATSum            float64                `xml:"totalVATSum,omitempty"`
	TotalSum               float64                `xml:"totalSum,omitempty"`
}

// OrderResponseItemDto mirrors the iiko DTO of the same name.
type OrderResponseItemDto struct {
	Gtin                 string      `xml:"gtin,omitempty"`
	InternalBuyerCode    string      `xml:"internalBuyerCode,omitempty"`
	InternalSupplierCode string      `xml:"internalSupplierCode,omitempty"`
	OrderLineNumber      int         `xml:"orderLineNumber,omitempty"`
	LineNumber           int         `xml:"lineNumber"`
	Name                 string      `xml:"name,omitempty"`
	Comment              string      `xml:"comment,omitempty"`
	RequestedQuantity    QuantityDto `xml:"requestedQuantity,omitempty"`
	ConfirmedQuantity    QuantityDto `xml:"confirmedQuantity"`
	PriceWithVAT         float64     `xml:"priceWithVat,omitempty"`
	SumWithVAT           float64     `xml:"sumWithVat"`
}

// QuantityDtoMeasureUnitDtoValues are the documented values of QuantityDto.MeasureUnitDto.
var QuantityDtoMeasureUnitDtoValues = []string{
	"KG",
	"PCE",
	"LT",
}

// QuantityDto mirrors the iiko DTO of the same name.
type QuantityDto struct {
	MeasureUnit       string            `xml:"measureUnit"` // KG PCE LT
	Quantity          float64           `xml:"quantity"`
	Container         ContainerDto__edi `xml:"container,omitempty"`
	ContainerQuantity float64           `xml:"containerQuantity,omitempty"`
}
