// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package events

// EventAttributeDto mirrors the iiko DTO of the same name.
type EventAttributeDto struct {
	Name  string `xml:"name,omitempty"`
	Value string `xml:"value,omitempty"`
	Type  string `xml:"type,omitempty"` // java.lang.Boolean java.lang.String java.util.Date resto.db.Guid
}

// EventAttributeMetadataDto mirrors the iiko DTO of the same name.
type EventAttributeMetadataDto struct {
	ID   string `xml:"id,omitempty"`   // read-only
	Name string `xml:"name,omitempty"` // read-only
}

// EventDto mirrors the iiko DTO of the same name.
type EventDto struct {
	ID           string              `xml:"id,omitempty"` // read-only
	Date         string              `xml:"date,omitempty"`
	DepartmentID string              `xml:"departmentId,omitempty"`
	Type         string              `xml:"type,omitempty"`
	Attribute    []EventAttributeDto `xml:"attribute,omitempty"`
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported EventDto: encoding/xml cannot skip them per field.
func (x *EventDto) StripReadOnly() {
	var zeroID string
	x.ID = zeroID
}

// EventGroupDto mirrors the iiko DTO of the same name.
type EventGroupDto struct {
	ID   string                 `xml:"id,omitempty"`   // read-only
	Name string                 `xml:"name,omitempty"` // read-only
	Type []EventTypeMetadataDto `xml:"type,omitempty"` // read-only
}

// EventTypeMetadataDtoEventSeverityValues are the documented values of EventTypeMetadataDto.EventSeverity.
var EventTypeMetadataDtoEventSeverityValues = []string{
	"0 = Low",
	"1 = Medium",
	"2 = High",
}

// EventTypeMetadataDto mirrors the iiko DTO of the same name.
type EventTypeMetadataDto struct {
	Attribute []EventAttributeMetadataDto `xml:"attribute,omitempty"` // read-only
	ID        string                      `xml:"id,omitempty"`        // read-only
	Name      string                      `xml:"name,omitempty"`      // read-only
	Severity  string                      `xml:"severity,omitempty"`  // read-only; 0 1 2
}

// EventsListDto mirrors the iiko DTO of the same name.
type EventsListDto struct {
	Event    []EventDto `xml:"event,omitempty"`
	Revision int        `xml:"revision,omitempty"` // read-only
}

// StripReadOnly zeroes the server-generated fields. Call it before re-sending
// an exported EventsListDto: encoding/xml cannot skip them per field.
func (x *EventsListDto) StripReadOnly() {
	var zeroRevision int
	x.Revision = zeroRevision
}

// EventsRequestDataDto mirrors the iiko DTO of the same name.
type EventsRequestDataDto struct {
	Events    []string `xml:"events>event"`
	OrderNums []string `xml:"orderNums>orderNum"`
}

// GroupsListDto mirrors the iiko DTO of the same name.
type GroupsListDto struct {
	Group []EventGroupDto `xml:"group,omitempty"` // read-only
}
