// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package nomenclature

import (
	"encoding/json"
)

// BarcodeContainerDto mirrors the iiko DTO of the same name.
type BarcodeContainerDto struct {
	Barcode     string `json:"barcode,omitempty"`
	ContainerID string `json:"containerId,omitempty"`
}

// BarcodeContainerDtoXML mirrors the iiko DTO of the same name.
type BarcodeContainerDtoXML struct {
	Barcode       string `xml:"barcode"`
	ContainerName string `xml:"containerName,omitempty"`
}

// ChoiceBindingDto mirrors the iiko DTO of the same name.
type ChoiceBindingDto struct {
	Modifier                             string             `json:"modifier,omitempty"`
	DefaultAmount                        int                `json:"defaultAmount,omitempty"`
	FreeOfChargeAmount                   int                `json:"freeOfChargeAmount,omitempty"`
	MinimumAmount                        int                `json:"minimumAmount,omitempty"`
	MaximumAmount                        int                `json:"maximumAmount,omitempty"`
	HideIfDefaultAmount                  bool               `json:"hideIfDefaultAmount,omitempty"`
	ChildModifiersHaveMinMaxRestrictions bool               `json:"childModifiersHaveMinMaxRestrictions,omitempty"`
	Splittable                           bool               `json:"splittable,omitempty"`
	ChildModifiers                       []ChoiceBindingDto `json:"childModifiers,omitempty"`
}

// ContainerDtoXML mirrors the iiko DTO of the same name.
type ContainerDtoXML struct {
	ID                    string  `xml:"id,omitempty"`
	Num                   string  `xml:"num,omitempty"`
	Name                  string  `xml:"name"`
	Count                 float64 `xml:"count,omitempty"`
	MinContainerWeight    float64 `xml:"minContainerWeight,omitempty"`
	MaxContainerWeight    float64 `xml:"maxContainerWeight,omitempty"`
	ContainerWeight       float64 `xml:"containerWeight,omitempty"`
	FullContainerWeight   float64 `xml:"fullContainerWeight,omitempty"`
	Density               float64 `xml:"density,omitempty"`
	BackwardRecalculation bool    `xml:"backwardRecalculation,omitempty"`
	Deleted               bool    `xml:"deleted"`
	UseInFront            bool    `xml:"useInFront,omitempty"`
}

// ContainerDto__nomenclature is Shape reconciled across domains. The docs for /resto/api/suppliers/{code}/pricelist show only a reduced field …
type ContainerDto__nomenclature struct {
	ID                  string  `json:"id,omitempty"` // read-only
	Num                 string  `json:"num"`
	Name                string  `json:"name"`
	Count               float64 `json:"count"`
	MinContainerWeight  float64 `json:"minContainerWeight,omitempty"`
	MaxContainerWeight  float64 `json:"maxContainerWeight,omitempty"`
	ContainerWeight     float64 `json:"containerWeight"`
	FullContainerWeight float64 `json:"fullContainerWeight"`
	UseInFront          bool    `json:"useInFront,omitempty"`
	Deleted             bool    `json:"deleted,omitempty"` // read-only
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x ContainerDto__nomenclature) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		Num                 string  `json:"num"`
		Name                string  `json:"name"`
		Count               float64 `json:"count"`
		MinContainerWeight  float64 `json:"minContainerWeight,omitempty"`
		MaxContainerWeight  float64 `json:"maxContainerWeight,omitempty"`
		ContainerWeight     float64 `json:"containerWeight"`
		FullContainerWeight float64 `json:"fullContainerWeight"`
		UseInFront          bool    `json:"useInFront,omitempty"`
	}{
		Num:                 x.Num,
		Name:                x.Name,
		Count:               x.Count,
		MinContainerWeight:  x.MinContainerWeight,
		MaxContainerWeight:  x.MaxContainerWeight,
		ContainerWeight:     x.ContainerWeight,
		FullContainerWeight: x.FullContainerWeight,
		UseInFront:          x.UseInFront,
	})
}

// DepartmentFilterDto mirrors the iiko DTO of the same name.
type DepartmentFilterDto struct {
	Departments []string `json:"departments,omitempty"`
	Excluding   bool     `json:"excluding,omitempty"`
}

// EntityDto mirrors the iiko DTO of the same name.
type EntityDto struct {
	ID       string `json:"id,omitempty"`
	Deleted  bool   `json:"deleted,omitempty"` // read-only
	Name     string `json:"name"`
	RootType string `json:"rootType,omitempty"` // read-only
	Code     string `json:"code,omitempty"`     // read-only
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x EntityDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		ID   string `json:"id,omitempty"`
		Name string `json:"name"`
	}{
		ID:   x.ID,
		Name: x.Name,
	})
}

// IdListDto mirrors the iiko DTO of the same name.
type IdListDto struct {
	Items []IdListItemDto `json:"items"`
}

// IdListItemDto mirrors the iiko DTO of the same name.
type IdListItemDto struct {
	ID string `json:"id"`
}

// ImageDto mirrors the iiko DTO of the same name.
type ImageDto struct {
	ID   string `json:"id,omitempty"` // read-only
	Data string `json:"data,omitempty"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x ImageDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		Data string `json:"data,omitempty"`
	}{
		Data: x.Data,
	})
}

// ProductDtoProductTypeValues are the documented values of ProductDto.ProductType.
var ProductDtoProductTypeValues = []string{
	"GOODS",
	"DISH",
	"PREPARED",
	"MODIFIER",
	"SERVICE",
	"RATE",
	"OUTER",
}

// ProductDto mirrors the iiko DTO of the same name.
type ProductDto struct {
	ID                     string                       `json:"id,omitempty"`
	Deleted                bool                         `json:"deleted,omitempty"` // read-only
	Name                   string                       `json:"name"`
	Description            string                       `json:"description,omitempty"`
	Num                    string                       `json:"num,omitempty"`
	Code                   string                       `json:"code,omitempty"`
	Parent                 string                       `json:"parent,omitempty"`
	Modifiers              []ChoiceBindingDto           `json:"modifiers,omitempty"`
	TaxCategory            string                       `json:"taxCategory,omitempty"`
	Category               string                       `json:"category,omitempty"` // also spelled productCategoryId
	AccountingCategory     string                       `json:"accountingCategory,omitempty"`
	Color                  RGBColorDto                  `json:"color,omitempty"`
	FontColor              RGBColorDto                  `json:"fontColor,omitempty"`
	FrontImageID           string                       `json:"frontImageId,omitempty"`
	Position               int                          `json:"position,omitempty"`
	MainUnit               string                       `json:"mainUnit"`
	ExcludedSections       []string                     `json:"excludedSections,omitempty"`
	DefaultSalePrice       float64                      `json:"defaultSalePrice,omitempty"`
	PlaceType              string                       `json:"placeType,omitempty"`
	DefaultIncludeInMenu   bool                         `json:"defaultIncludeInMenu,omitempty"` // also spelled defaultIncludedInMenu
	Type                   string                       `json:"type"`                           // GOODS DISH PREPARED SERVICE MODIFIER OUTER RATE
	UnitWeight             float64                      `json:"unitWeight,omitempty"`           // also spelled weight
	UnitCapacity           float64                      `json:"unitCapacity,omitempty"`
	NotInStoreMovement     bool                         `json:"notInStoreMovement,omitempty"`
	Containers             []ContainerDto__nomenclature `json:"containers,omitempty"`
	ModifierSchemaID       string                       `json:"modifierSchemaId,omitempty"`
	ProductScaleID         string                       `json:"productScaleId,omitempty"`
	ColdLossPercent        float64                      `json:"coldLossPercent,omitempty"`
	HotLossPercent         float64                      `json:"hotLossPercent,omitempty"`
	AllergenGroups         []string                     `json:"allergenGroups,omitempty"`
	CanSetOpenPrice        bool                         `json:"canSetOpenPrice,omitempty"`
	UseBalanceForSell      bool                         `json:"useBalanceForSell,omitempty"` // read-only
	Barcodes               []BarcodeContainerDto        `json:"barcodes,omitempty"`
	EstimatedPurchasePrice float64                      `json:"estimatedPurchasePrice,omitempty"`
}

// UnmarshalJSON accepts every documented spelling of ProductDto's ambiguous fields.
func (x *ProductDto) UnmarshalJSON(data []byte) error {
	type plain ProductDto
	var v struct {
		plain
		Alias0_0 string  `json:"productCategoryId"`
		Alias1_0 bool    `json:"defaultIncludedInMenu"`
		Alias2_0 float64 `json:"weight"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = ProductDto(v.plain)
	if x.Category == "" {
		x.Category = v.Alias0_0
	}
	if !x.DefaultIncludeInMenu {
		x.DefaultIncludeInMenu = v.Alias1_0
	}
	if x.UnitWeight == 0 {
		x.UnitWeight = v.Alias2_0
	}
	return nil
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x ProductDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		ID                     string                       `json:"id,omitempty"`
		Name                   string                       `json:"name"`
		Description            string                       `json:"description,omitempty"`
		Num                    string                       `json:"num,omitempty"`
		Code                   string                       `json:"code,omitempty"`
		Parent                 string                       `json:"parent,omitempty"`
		Modifiers              []ChoiceBindingDto           `json:"modifiers,omitempty"`
		TaxCategory            string                       `json:"taxCategory,omitempty"`
		Category               string                       `json:"category,omitempty"`
		AccountingCategory     string                       `json:"accountingCategory,omitempty"`
		Color                  RGBColorDto                  `json:"color,omitempty"`
		FontColor              RGBColorDto                  `json:"fontColor,omitempty"`
		FrontImageID           string                       `json:"frontImageId,omitempty"`
		Position               int                          `json:"position,omitempty"`
		MainUnit               string                       `json:"mainUnit"`
		ExcludedSections       []string                     `json:"excludedSections,omitempty"`
		DefaultSalePrice       float64                      `json:"defaultSalePrice,omitempty"`
		PlaceType              string                       `json:"placeType,omitempty"`
		DefaultIncludeInMenu   bool                         `json:"defaultIncludeInMenu,omitempty"`
		Type                   string                       `json:"type"`
		UnitWeight             float64                      `json:"unitWeight,omitempty"`
		UnitCapacity           float64                      `json:"unitCapacity,omitempty"`
		NotInStoreMovement     bool                         `json:"notInStoreMovement,omitempty"`
		Containers             []ContainerDto__nomenclature `json:"containers,omitempty"`
		ModifierSchemaID       string                       `json:"modifierSchemaId,omitempty"`
		ProductScaleID         string                       `json:"productScaleId,omitempty"`
		ColdLossPercent        float64                      `json:"coldLossPercent,omitempty"`
		HotLossPercent         float64                      `json:"hotLossPercent,omitempty"`
		AllergenGroups         []string                     `json:"allergenGroups,omitempty"`
		CanSetOpenPrice        bool                         `json:"canSetOpenPrice,omitempty"`
		Barcodes               []BarcodeContainerDto        `json:"barcodes,omitempty"`
		EstimatedPurchasePrice float64                      `json:"estimatedPurchasePrice,omitempty"`
	}{
		ID:                     x.ID,
		Name:                   x.Name,
		Description:            x.Description,
		Num:                    x.Num,
		Code:                   x.Code,
		Parent:                 x.Parent,
		Modifiers:              x.Modifiers,
		TaxCategory:            x.TaxCategory,
		Category:               x.Category,
		AccountingCategory:     x.AccountingCategory,
		Color:                  x.Color,
		FontColor:              x.FontColor,
		FrontImageID:           x.FrontImageID,
		Position:               x.Position,
		MainUnit:               x.MainUnit,
		ExcludedSections:       x.ExcludedSections,
		DefaultSalePrice:       x.DefaultSalePrice,
		PlaceType:              x.PlaceType,
		DefaultIncludeInMenu:   x.DefaultIncludeInMenu,
		Type:                   x.Type,
		UnitWeight:             x.UnitWeight,
		UnitCapacity:           x.UnitCapacity,
		NotInStoreMovement:     x.NotInStoreMovement,
		Containers:             x.Containers,
		ModifierSchemaID:       x.ModifierSchemaID,
		ProductScaleID:         x.ProductScaleID,
		ColdLossPercent:        x.ColdLossPercent,
		HotLossPercent:         x.HotLossPercent,
		AllergenGroups:         x.AllergenGroups,
		CanSetOpenPrice:        x.CanSetOpenPrice,
		Barcodes:               x.Barcodes,
		EstimatedPurchasePrice: x.EstimatedPurchasePrice,
	})
}

// ProductDtoXMLProductTypeEnumLegacyXMLValues are the documented values of ProductDtoXML.ProductType_enum (legacy XML).
var ProductDtoXMLProductTypeEnumLegacyXMLValues = []string{
	"GOODS",
	"DISH",
	"PREPARED",
	"SERVICE",
	"MODIFIER",
	"OUTER",
	"PETROL",
	"RATE",
}

// ProductDtoXMLProductGroupTypeEnumLegacyXMLValues are the documented values of ProductDtoXML.ProductGroupType_enum (legacy XML).
var ProductDtoXMLProductGroupTypeEnumLegacyXMLValues = []string{
	"PRODUCTS",
	"MODIFIERS",
}

// ProductDtoXML mirrors the iiko DTO of the same name.
type ProductDtoXML struct {
	ID               string                   `xml:"id,omitempty"`
	ParentID         string                   `xml:"parentId,omitempty"`
	Num              string                   `xml:"num,omitempty"`
	Code             string                   `xml:"code,omitempty"`
	Name             string                   `xml:"name"`
	ProductType      string                   `xml:"productType,omitempty"`      // GOODS DISH PREPARED SERVICE MODIFIER OUTER PETROL RATE
	ProductGroupType string                   `xml:"productGroupType,omitempty"` // PRODUCTS MODIFIERS
	CookingPlaceType string                   `xml:"cookingPlaceType,omitempty"`
	MainUnit         string                   `xml:"mainUnit,omitempty"`
	ProductCategory  string                   `xml:"productCategory,omitempty"`
	Containers       []ContainerDtoXML        `xml:"containers,omitempty"`
	Barcodes         []BarcodeContainerDtoXML `xml:"barcodes,omitempty"`
}

// ProductGroupDto mirrors the iiko DTO of the same name.
type ProductGroupDto struct {
	ID                 string              `json:"id,omitempty"`
	Deleted            bool                `json:"deleted,omitempty"` // read-only
	Name               string              `json:"name"`
	Description        string              `json:"description,omitempty"`
	Num                string              `json:"num,omitempty"`  // read-only
	Code               string              `json:"code,omitempty"` // read-only
	Parent             string              `json:"parent,omitempty"`
	Modifiers          []ChoiceBindingDto  `json:"modifiers,omitempty"` // read-only
	TaxCategory        string              `json:"taxCategory,omitempty"`
	Category           string              `json:"category,omitempty"`
	AccountingCategory string              `json:"accountingCategory,omitempty"` // read-only
	Color              RGBColorDto         `json:"color,omitempty"`
	FontColor          RGBColorDto         `json:"fontColor,omitempty"`
	FrontImageID       string              `json:"frontImageId,omitempty"`
	Position           int                 `json:"position,omitempty"`
	VisibilityFilter   DepartmentFilterDto `json:"visibilityFilter,omitempty"` // read-only
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x ProductGroupDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		ID           string      `json:"id,omitempty"`
		Name         string      `json:"name"`
		Description  string      `json:"description,omitempty"`
		Parent       string      `json:"parent,omitempty"`
		TaxCategory  string      `json:"taxCategory,omitempty"`
		Category     string      `json:"category,omitempty"`
		Color        RGBColorDto `json:"color,omitempty"`
		FontColor    RGBColorDto `json:"fontColor,omitempty"`
		FrontImageID string      `json:"frontImageId,omitempty"`
		Position     int         `json:"position,omitempty"`
	}{
		ID:           x.ID,
		Name:         x.Name,
		Description:  x.Description,
		Parent:       x.Parent,
		TaxCategory:  x.TaxCategory,
		Category:     x.Category,
		Color:        x.Color,
		FontColor:    x.FontColor,
		FrontImageID: x.FrontImageID,
		Position:     x.Position,
	})
}

// ProductScaleBindingDto mirrors the iiko DTO of the same name.
type ProductScaleBindingDto struct {
	ID           string           `json:"id"`
	ProductSizes []ProductSizeDto `json:"productSizes,omitempty"`
}

// ProductScaleDto mirrors the iiko DTO of the same name.
type ProductScaleDto struct {
	ID           string           `json:"id,omitempty"`
	Deleted      bool             `json:"deleted,omitempty"` // read-only
	Name         string           `json:"name"`
	ProductSizes []ProductSizeDto `json:"productSizes,omitempty"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x ProductScaleDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		ID           string           `json:"id,omitempty"`
		Name         string           `json:"name"`
		ProductSizes []ProductSizeDto `json:"productSizes,omitempty"`
	}{
		ID:           x.ID,
		Name:         x.Name,
		ProductSizes: x.ProductSizes,
	})
}

// ProductSizeDto mirrors the iiko DTO of the same name.
type ProductSizeDto struct {
	ID        string                 `json:"id,omitempty"`
	Deleted   bool                   `json:"deleted,omitempty"` // read-only
	Name      string                 `json:"name,omitempty"`
	ShortName string                 `json:"shortName,omitempty"`
	Priority  int                    `json:"priority,omitempty"`
	Default   bool                   `json:"default,omitempty"`
	Disabled  bool                   `json:"disabled,omitempty"`
	Factors   []ProductSizeFactorDto `json:"factors,omitempty"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x ProductSizeDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		ID        string                 `json:"id,omitempty"`
		Name      string                 `json:"name,omitempty"`
		ShortName string                 `json:"shortName,omitempty"`
		Priority  int                    `json:"priority,omitempty"`
		Default   bool                   `json:"default,omitempty"`
		Disabled  bool                   `json:"disabled,omitempty"`
		Factors   []ProductSizeFactorDto `json:"factors,omitempty"`
	}{
		ID:        x.ID,
		Name:      x.Name,
		ShortName: x.ShortName,
		Priority:  x.Priority,
		Default:   x.Default,
		Disabled:  x.Disabled,
		Factors:   x.Factors,
	})
}

// ProductSizeFactorDto mirrors the iiko DTO of the same name.
type ProductSizeFactorDto struct {
	StartNumber int     `json:"startNumber,omitempty"`
	Factor      float64 `json:"factor,omitempty"`
}

// ProductsAndGroupsDto mirrors the iiko DTO of the same name.
type ProductsAndGroupsDto struct {
	Products      json.RawMessage `json:"products,omitempty"`
	ProductGroups json.RawMessage `json:"productGroups,omitempty"`
}

// QuickLabelDto mirrors the iiko DTO of the same name.
type QuickLabelDto struct {
	Day        int    `json:"day,omitempty"`
	Page       int    `json:"page"`
	X          int    `json:"x"`
	Y          int    `json:"y"`
	EntityID   string `json:"entityId,omitempty"`
	EntityType string `json:"entityType,omitempty"` // read-only; PRODUCT PRODUCT_GROUP
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x QuickLabelDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		Day      int    `json:"day,omitempty"`
		Page     int    `json:"page"`
		X        int    `json:"x"`
		Y        int    `json:"y"`
		EntityID string `json:"entityId,omitempty"`
	}{
		Day:      x.Day,
		Page:     x.Page,
		X:        x.X,
		Y:        x.Y,
		EntityID: x.EntityID,
	})
}

// QuickMenuDto mirrors the iiko DTO of the same name.
type QuickMenuDto struct {
	ID               string          `json:"id,omitempty"`      // read-only
	Deleted          bool            `json:"deleted,omitempty"` // read-only
	DependsOnWeekDay bool            `json:"dependsOnWeekDay,omitempty"`
	DepartmentID     string          `json:"departmentId,omitempty"`
	SectionID        string          `json:"sectionId,omitempty"`
	PageNames        []string        `json:"pageNames,omitempty"`
	Labels           []QuickLabelDto `json:"labels,omitempty"`
}

// MarshalJSON omits the read-only fields iiko rejects on the way in.
func (x QuickMenuDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		DependsOnWeekDay bool            `json:"dependsOnWeekDay,omitempty"`
		DepartmentID     string          `json:"departmentId,omitempty"`
		SectionID        string          `json:"sectionId,omitempty"`
		PageNames        []string        `json:"pageNames,omitempty"`
		Labels           []QuickLabelDto `json:"labels,omitempty"`
	}{
		DependsOnWeekDay: x.DependsOnWeekDay,
		DepartmentID:     x.DepartmentID,
		SectionID:        x.SectionID,
		PageNames:        x.PageNames,
		Labels:           x.Labels,
	})
}

// RGBColorDto mirrors the iiko DTO of the same name.
type RGBColorDto struct {
	Red   int `json:"red,omitempty"`
	Green int `json:"green,omitempty"`
	Blue  int `json:"blue,omitempty"`
}
