// Code generated by tools/gen/server from research/dtos.yaml. DO NOT EDIT.

// Field names, types and the read-only and alias marks all come from the
// catalog; change research/dtos.yaml and re-run `make gen`, never this file.
package reports

import (
	"encoding/json"
)

// AccountGroupAccountGroupValues are the documented values of AccountGroup.AccountGroup.
var AccountGroupAccountGroupValues = []string{
	"ASSETS",
	"LIABILITIES",
	"EQUITY",
	"INCOME_EXPENSES",
}

// AccountTypeAccountTypeValues are the documented values of AccountType.AccountType.
var AccountTypeAccountTypeValues = []string{
	"CASH",
	"ACCOUNTS_RECEIVABLE",
	"DEBTS_OF_EMPLOYEES",
	"CURRENT_ASSET",
	"OTHER_CURRENT_ASSET",
	"INVENTORY_ASSETS",
	"EMPLOYEES_LIABILITY",
	"ACCOUNTS_PAYABLE",
	"CLIENTS_LIABILITY",
	"OTHER_CURRENT_LIABILITY",
	"LONG_TERM_LIABILITY",
	"EQUITY",
	"COST_OF_GOODS_SOLD",
	"INCOME",
	"EXPENSES",
	"OTHER_INCOME",
	"OTHER_EXPENSES",
}

// AlcoholClassTypeAlcoholClassTypeValues are the documented values of AlcoholClassType.AlcoholClassType.
var AlcoholClassTypeAlcoholClassTypeValues = []string{
	"STRONG",
	"BEER",
}

// BalanceCounteragentEntry mirrors the iiko DTO of the same name.
type BalanceCounteragentEntry struct {
	Account      string  `json:"account,omitempty"`
	Counteragent string  `json:"counteragent,omitempty"`
	Department   string  `json:"department,omitempty"`
	Sum          float64 `json:"sum,omitempty"`
}

// BalanceStoreEntry mirrors the iiko DTO of the same name.
type BalanceStoreEntry struct {
	Store   string  `json:"store,omitempty"`
	Product string  `json:"product,omitempty"`
	Amount  float64 `json:"amount,omitempty"`
	Sum     float64 `json:"sum,omitempty"`
}

// BanquetFlagBanquetFlagValues are the documented values of BanquetFlag.BanquetFlag.
var BanquetFlagBanquetFlagValues = []string{
	"TRUE",
	"FALSE",
}

// BudgetPlanItemDtoBudgetPlanItemValueTypeValues are the documented values of BudgetPlanItemDto.BudgetPlanItemValueType.
var BudgetPlanItemDtoBudgetPlanItemValueTypeValues = []string{
	"ABSOLUTE",
	"PERCENT",
	"AUTOMATIC",
}

// BudgetPlanItemDto mirrors the iiko DTO of the same name.
type BudgetPlanItemDto struct {
	Date      string  `xml:"date,omitempty"`
	PlanValue float64 `xml:"planValue,omitempty"`
	ValueType string  `xml:"valueType,omitempty"`
}

// CashFlowCategoryTypeCashFlowCategoryTypeValues are the documented values of CashFlowCategoryType.CashFlowCategoryType.
var CashFlowCategoryTypeCashFlowCategoryTypeValues = []string{
	"OPERATIONAL",
	"INVESTMENT",
	"FINANCE",
}

// CounteragentTypeCounteragentTypeValues are the documented values of CounteragentType.CounteragentType.
var CounteragentTypeCounteragentTypeValues = []string{
	"NONE",
	"COUNTERAGENT",
	"EMPLOYEE",
	"SUPPLIER",
	"CLIENT",
	"INTERNAL_SUPPLIER",
}

// DayDishValueDto mirrors the iiko DTO of the same name.
type DayDishValueDto struct {
	Date        string  `xml:"date,omitempty"`
	ProductID   string  `xml:"productId,omitempty"`
	ProductName string  `xml:"productName,omitempty"`
	Value       float64 `xml:"value,omitempty"`
}

// DeliveryConsolidatedRow mirrors the iiko DTO of the same name.
type DeliveryConsolidatedRow struct {
	AvgReceipt           float64 `xml:"avgReceipt,omitempty"`
	Date                 string  `xml:"date,omitempty"`
	DishAmount           float64 `xml:"dishAmount,omitempty"`
	DishAmountPerOrder   float64 `xml:"dishAmountPerOrder,omitempty"`
	OrderCount           float64 `xml:"orderCount,omitempty"`
	OrderCountCourier    float64 `xml:"orderCountCourier,omitempty"`
	OrderCountPickup     float64 `xml:"orderCountPickup,omitempty"`
	PlanExecutionPercent float64 `xml:"planExecutionPercent,omitempty"`
	RatioCostWriteoff    float64 `xml:"ratioCostWriteoff,omitempty"`
	Revenue              float64 `xml:"revenue,omitempty"`
}

// DeliveryCourierMetricMetricTypeValues are the documented values of DeliveryCourierMetric.MetricType.
var DeliveryCourierMetricMetricTypeValues = []string{
	"AVERAGE",
	"TARGET",
	"MAXIMUM",
}

// DeliveryCourierMetric mirrors the iiko DTO of the same name.
type DeliveryCourierMetric struct {
	DoubledOrders float64 `xml:"doubledOrders,omitempty"`
	MetricType    string  `xml:"metricType,omitempty"`
	OnTheWayTime  float64 `xml:"onTheWayTime,omitempty"`
	OrderCount    float64 `xml:"orderCount,omitempty"`
	TotalTime     float64 `xml:"totalTime,omitempty"`
	TripledOrders float64 `xml:"tripledOrders,omitempty"`
}

// DeliveryCourierRow mirrors the iiko DTO of the same name.
type DeliveryCourierRow struct {
	Courier string                  `xml:"courier,omitempty"`
	Metrics []DeliveryCourierMetric `xml:"metrics,omitempty"`
}

// DeliveryFlagDeliveryFlagValues are the documented values of DeliveryFlag.DeliveryFlag.
var DeliveryFlagDeliveryFlagValues = []string{
	"DELIVERY_ORDER",
	"ORDER_WITHOUT_DELIVERY",
}

// DeliveryHalfHourMetricDeliveryTypeValues are the documented values of DeliveryHalfHourMetric.DeliveryType.
var DeliveryHalfHourMetricDeliveryTypeValues = []string{
	"COURIER",
	"PICKUP",
}

// DeliveryHalfHourMetric mirrors the iiko DTO of the same name.
type DeliveryHalfHourMetric struct {
	AvgDishAmountPerReceipt float64 `xml:"avgDishAmountPerReceipt,omitempty"`
	AvgReceipt              float64 `xml:"avgReceipt,omitempty"`
	DeliveryType            string  `xml:"deliveryType,omitempty"`
	DishAmount              float64 `xml:"dishAmount,omitempty"`
	OrderCount              float64 `xml:"orderCount,omitempty"`
}

// DeliveryHalfHourRow mirrors the iiko DTO of the same name.
type DeliveryHalfHourRow struct {
	HalfHourDate string                   `xml:"halfHourDate,omitempty"`
	Metrics      []DeliveryHalfHourMetric `xml:"metrics,omitempty"`
}

// DeliveryLoyaltyRegion mirrors the iiko DTO of the same name.
type DeliveryLoyaltyRegion struct {
	OrderCount float64 `xml:"orderCount,omitempty"`
	Region     string  `xml:"region,omitempty"`
}

// DeliveryLoyaltyRowMetricTypeValues are the documented values of DeliveryLoyaltyRow.MetricType.
var DeliveryLoyaltyRowMetricTypeValues = []string{
	"AVERAGE",
	"MINIMUM",
	"MAXIMUM",
}

// DeliveryLoyaltyRow mirrors the iiko DTO of the same name.
type DeliveryLoyaltyRow struct {
	Date               string                  `xml:"date,omitempty"`
	MetricType         string                  `xml:"metricType,omitempty"`
	NewGuestCount      float64                 `xml:"newGuestCount,omitempty"`
	OrderCountPerGuest float64                 `xml:"orderCountPerGuest,omitempty"`
	Regions            []DeliveryLoyaltyRegion `xml:"regions,omitempty"`
	TotalOrderCount    float64                 `xml:"totalOrderCount,omitempty"`
}

// DeliveryOrderCycleRow mirrors the iiko DTO of the same name.
type DeliveryOrderCycleRow struct {
	CuttingTime      float64 `xml:"cuttingTime,omitempty"`
	InRestaurantTime float64 `xml:"inRestaurantTime,omitempty"`
	OnShelfTime      float64 `xml:"onShelfTime,omitempty"`
	OnTheWayTime     float64 `xml:"onTheWayTime,omitempty"`
	PizzaTime        float64 `xml:"pizzaTime,omitempty"`
	TotalTime        float64 `xml:"totalTime,omitempty"`
	MetricType       string  `xml:"metricType,omitempty"`
}

// DeliveryRegionRow mirrors the iiko DTO of the same name.
type DeliveryRegionRow struct {
	AverageDeliveryTime    float64 `xml:"averageDeliveryTime,omitempty"`
	DeliveredOrdersPercent float64 `xml:"deliveredOrdersPercent,omitempty"`
	MaxOrderCountDay       float64 `xml:"maxOrderCountDay,omitempty"`
	OrderCount             float64 `xml:"orderCount,omitempty"`
	Region                 string  `xml:"region,omitempty"`
}

// DepartmentTypeDepartmentTypeValues are the documented values of DepartmentType.DepartmentType.
var DepartmentTypeDepartmentTypeValues = []string{
	"CORPORATION",
	"JURPERSON",
	"ORGDEVELOPMENT",
	"DEPARTMENT",
	"MANUFACTURE",
	"CENTRALSTORE",
	"CENTRALOFFICE",
	"SALEPOINT",
	"STORE",
}

// DishRemovalTypeDishRemovalTypeValues are the documented values of DishRemovalType.DishRemovalType.
var DishRemovalTypeDishRemovalTypeValues = []string{
	"DELETED_WITHOUT_WRITEOFF",
	"DELETED_WITH_WRITEOFF",
	"NOT_DELETED",
}

// DocumentTypeDocumentTypeValues are the documented values of DocumentType.DocumentType.
var DocumentTypeDocumentTypeValues = []string{
	"INCOMING_INVOICE",
	"INCOMING_INVENTORY",
	"INCOMING_SERVICE",
	"OUTGOING_SERVICE",
	"WRITEOFF_DOCUMENT",
	"SALES_DOCUMENT",
	"SESSION_ACCEPTANCE",
	"INTERNAL_TRANSFER",
	"OUTGOING_INVOICE",
	"RETURNED_INVOICE",
	"PRODUCTION_DOCUMENT",
	"TRANSFORMATION_DOCUMENT",
	"PRODUCTION_ORDER",
	"CONSOLIDATED_ORDER",
	"PREPARED_REGISTER",
	"MENU_CHANGE",
	"PRODUCT_REPLACEMENT",
	"SALES_RETURN_DOCUMENT",
	"DISASSEMBLE_DOCUMENT",
	"PAYROLL",
	"INCOMING_CASH_ORDER",
	"OUTGOING_CASH_ORDER",
}

// EgaisBRegDto mirrors the iiko DTO of the same name.
type EgaisBRegDto struct {
	SourceRarID     string            `json:"sourceRarId,omitempty"`
	AlcCode         string            `json:"alcCode,omitempty"`
	MarksOnBalance  EgaisMarkStateDto `json:"marksOnBalance,omitempty"`
	MarksWrittenOff EgaisMarkStateDto `json:"marksWrittenOff,omitempty"`
}

// EgaisMarkStateDto mirrors the iiko DTO of the same name.
type EgaisMarkStateDto struct {
	DateTo string `json:"dateTo,omitempty"`
}

// EgaisMarksListResponse mirrors the iiko DTO of the same name.
type EgaisMarksListResponse struct {
	Revision      int          `json:"revision"`
	FullUpdate    bool         `json:"fullUpdate"`
	MarksByBRegID EgaisBRegDto `json:"marksByBRegId,omitempty"`
}

// GoodsTypeGoodsTypeValues are the documented values of GoodsType.GoodsType.
var GoodsTypeGoodsTypeValues = []string{
	"DISH",
	"GOOD",
	"MODIFIER",
}

// IngredientEntryDto mirrors the iiko DTO of the same name.
type IngredientEntryDto struct {
	AmountInMainUnit        float64 `xml:"amountInMainUnit,omitempty"`
	AmountInMeasureUnit     float64 `xml:"amountInMeasureUnit,omitempty"`
	AmountMiddleMainUnit    float64 `xml:"amountMiddleMainUnit,omitempty"`
	AmountMiddleMeasureUnit float64 `xml:"amountMiddleMeasureUnit,omitempty"`
	AmountOutMainUnit       float64 `xml:"amountOutMainUnit,omitempty"`
	AmountOutMeasureUnit    float64 `xml:"amountOutMeasureUnit,omitempty"`
	ColdLoss                float64 `xml:"coldLoss,omitempty"`
	CostNorm                float64 `xml:"costNorm,omitempty"`
	DishCostNorm            float64 `xml:"dishCostNorm,omitempty"`
	DishSalePrice           float64 `xml:"dishSalePrice,omitempty"`
	HotLoss                 float64 `xml:"hotLoss,omitempty"`
	ItemID                  string  `xml:"itemId,omitempty"`
	ItemParentID            string  `xml:"itemParentId,omitempty"`
	Name                    string  `xml:"name,omitempty"`
	Num                     string  `xml:"num,omitempty"`
	Product                 string  `xml:"product,omitempty"`
	ProductInDishCost       float64 `xml:"productInDishCost,omitempty"`
	SourceProductCostNorm   float64 `xml:"sourceProductCostNorm,omitempty"`
	TreeLevel               int     `xml:"treeLevel"`
	Unit                    string  `xml:"unit,omitempty"`
}

// IsCashFlowAccountIsCashFlowAccountValues are the documented values of IsCashFlowAccount.IsCashFlowAccount.
var IsCashFlowAccountIsCashFlowAccountValues = []string{
	"CASH_FLOW",
	"NOT_CASH_FLOW",
}

// KeyValue mirrors the iiko DTO of the same name.
type KeyValue struct {
	K string `xml:"k,omitempty"`
	V string `xml:"v,omitempty"`
}

// OlapColumnDescriptorOlapFieldTypeValues are the documented values of OlapColumnDescriptor.OlapFieldType.
var OlapColumnDescriptorOlapFieldTypeValues = []string{
	"ENUM",
	"STRING",
	"ID",
	"DATETIME",
	"INTEGER",
	"PERCENT",
	"DURATION_IN_SECONDS",
	"AMOUNT",
	"MONEY",
}

// OlapColumnDescriptor mirrors the iiko DTO of the same name.
type OlapColumnDescriptor struct {
	Name               string   `json:"name,omitempty"`
	Type               string   `json:"type,omitempty"`
	AggregationAllowed bool     `json:"aggregationAllowed"`
	GroupingAllowed    bool     `json:"groupingAllowed"`
	FilteringAllowed   bool     `json:"filteringAllowed"`
	Tags               []string `json:"tags,omitempty"`
}

// OlapFieldsDeliveries mirrors the iiko DTO of the same name.
type OlapFieldsDeliveries struct {
	CloseTime                        string `json:"CloseTime,omitempty"`
	DeliveryActualTime               string `json:"Delivery.ActualTime,omitempty"`
	DeliveryAddress                  string `json:"Delivery.Address,omitempty"`
	DeliveryBillTime                 string `json:"Delivery.BillTime,omitempty"`
	DeliveryCancelCause              string `json:"Delivery.CancelCause,omitempty"`
	DeliveryCity                     string `json:"Delivery.City,omitempty"`
	DeliveryCloseTime                string `json:"Delivery.CloseTime,omitempty"`
	DeliveryCookingToSendDuration    string `json:"Delivery.CookingToSendDuration,omitempty"`
	DeliveryCourier                  string `json:"Delivery.Courier,omitempty"`
	DeliveryCustomerCardNumber       string `json:"Delivery.CustomerCardNumber,omitempty"`
	DeliveryCustomerCardType         string `json:"Delivery.CustomerCardType,omitempty"`
	DeliveryCustomerComment          string `json:"Delivery.CustomerComment,omitempty"`
	DeliveryCustomerCreatedDateTyped string `json:"Delivery.CustomerCreatedDateTyped,omitempty"` // also spelled Delivery.CustomerCreatedDate
	DeliveryCustomerMarketingSource  string `json:"Delivery.CustomerMarketingSource,omitempty"`
	DeliveryCustomerName             string `json:"Delivery.CustomerName,omitempty"`
	DeliveryDelay                    string `json:"Delivery.Delay,omitempty"`
	DeliveryDelayAvg                 string `json:"Delivery.DelayAvg,omitempty"`
	DeliveryDeliveryComment          string `json:"Delivery.DeliveryComment,omitempty"`
	DeliveryDeliveryOperator         string `json:"Delivery.DeliveryOperator,omitempty"`
	DeliveryEmail                    string `json:"Delivery.Email,omitempty"`
	DeliveryExpectedTime             string `json:"Delivery.ExpectedTime,omitempty"`
	DeliveryMarketingSource          string `json:"Delivery.MarketingSource,omitempty"`
	DeliveryNumber                   string `json:"Delivery.Number,omitempty"`
	DeliveryPhone                    string `json:"Delivery.Phone,omitempty"`
	DeliveryPrintTime                string `json:"Delivery.PrintTime,omitempty"`
	DeliveryRegion                   string `json:"Delivery.Region,omitempty"`
	DeliverySendTime                 string `json:"Delivery.SendTime,omitempty"`
	DeliveryServiceType              string `json:"Delivery.ServiceType,omitempty"`
	DeliverySourceKey                string `json:"Delivery.SourceKey,omitempty"`
	DeliveryStreet                   string `json:"Delivery.Street,omitempty"`
	DeliveryWayDuration              string `json:"Delivery.WayDuration,omitempty"`
	DeliveryWayDurationAvg           string `json:"Delivery.WayDurationAvg,omitempty"`
	DeliveryWayDurationSum           string `json:"Delivery.WayDurationSum,omitempty"`
	DishServicePrintTimeMax          string `json:"DishServicePrintTime.Max,omitempty"`
	DeliveryCustomerPhone            string `json:"Delivery.CustomerPhone,omitempty"`
}

// UnmarshalJSON accepts every documented spelling of OlapFieldsDeliveries's ambiguous fields.
func (x *OlapFieldsDeliveries) UnmarshalJSON(data []byte) error {
	type plain OlapFieldsDeliveries
	var v struct {
		plain
		Alias0_0 string `json:"Delivery.CustomerCreatedDate"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = OlapFieldsDeliveries(v.plain)
	if x.DeliveryCustomerCreatedDateTyped == "" {
		x.DeliveryCustomerCreatedDateTyped = v.Alias0_0
	}
	return nil
}

// OlapFieldsSales mirrors the iiko DTO of the same name.
type OlapFieldsSales struct {
	AuthUser                                    string `json:"AuthUser,omitempty"`
	Banquet                                     string `json:"Banquet,omitempty"`
	BonusCardNumber                             string `json:"Bonus.CardNumber,omitempty"`
	BonusSum                                    string `json:"Bonus.Sum,omitempty"`
	BonusType                                   string `json:"Bonus.Type,omitempty"`
	Card                                        string `json:"Card,omitempty"`
	CardNumber                                  string `json:"CardNumber,omitempty"`
	CardOwner                                   string `json:"CardOwner,omitempty"`
	CardType                                    string `json:"CardType,omitempty"`
	Cashier                                     string `json:"Cashier,omitempty"`
	CashLocation                                string `json:"CashLocation,omitempty"`
	CashRegisterName                            string `json:"CashRegisterName,omitempty"`
	CloseTime                                   string `json:"CloseTime,omitempty"`
	Comment                                     string `json:"Comment,omitempty"`
	Conception                                  string `json:"Conception,omitempty"`
	CookingPlace                                string `json:"CookingPlace,omitempty"`
	CreditUser                                  string `json:"CreditUser,omitempty"`
	DayOfWeekOpen                               string `json:"DayOfWeekOpen,omitempty"`
	DeletedWithWriteoff                         string `json:"DeletedWithWriteoff,omitempty"`
	DeletionComment                             string `json:"DeletionComment,omitempty"`
	DeliveryIsDelivery                          string `json:"Delivery.IsDelivery,omitempty"`
	Department                                  string `json:"Department,omitempty"`
	DiscountPercent                             string `json:"DiscountPercent,omitempty"`
	DiscountSum                                 string `json:"DiscountSum,omitempty"`
	DiscountWithoutVAT                          string `json:"discountWithoutVAT,omitempty"`
	DishAmountInt                               string `json:"DishAmountInt,omitempty"`
	DishCategory                                string `json:"DishCategory,omitempty"`
	DishCode                                    string `json:"DishCode,omitempty"`
	DishCodeQuick                               string `json:"DishCode.Quick,omitempty"`
	DishDiscountSumInt                          string `json:"DishDiscountSumInt,omitempty"`
	DishDiscountSumIntAverage                   string `json:"DishDiscountSumInt.average,omitempty"`
	DishDiscountSumIntAverageByGuest            string `json:"DishDiscountSumInt.averageByGuest,omitempty"`
	DishDiscountSumIntAveragePrice              string `json:"DishDiscountSumInt.averagePrice,omitempty"`
	DishDiscountSumIntWithoutVAT                string `json:"DishDiscountSumInt.withoutVAT,omitempty"`
	DishForeignName                             string `json:"DishForeignName,omitempty"`
	DishFullName                                string `json:"DishFullName,omitempty"`
	DishGroup                                   string `json:"DishGroup,omitempty"`
	DishGroupHierarchy                          string `json:"DishGroup.Hierarchy,omitempty"`
	DishGroupNum                                string `json:"DishGroup.Num,omitempty"`
	DishGroupSecondParent                       string `json:"DishGroup.SecondParent,omitempty"`
	DishGroupThirdParent                        string `json:"DishGroup.ThirdParent,omitempty"`
	DishGroupTopParent                          string `json:"DishGroup.TopParent,omitempty"`
	DishMeasureUnit                             string `json:"DishMeasureUnit,omitempty"`
	DishName                                    string `json:"DishName,omitempty"`
	DishReturnSum                               string `json:"DishReturnSum,omitempty"`
	DishServicePrintTime                        string `json:"DishServicePrintTime,omitempty"`
	DishServicePrintTimeMax                     string `json:"DishServicePrintTime.Max,omitempty"`
	DishServicePrintTimeOpenToLastPrintDuration string `json:"DishServicePrintTime.OpenToLastPrintDuration,omitempty"`
	DishSumInt                                  string `json:"DishSumInt,omitempty"`
	DishType                                    string `json:"DishType,omitempty"`
	FullSum                                     string `json:"fullSum,omitempty"`
	GuestNum                                    string `json:"GuestNum,omitempty"`
	GuestNumAvg                                 string `json:"GuestNum.Avg,omitempty"`
	HourClose                                   string `json:"HourClose,omitempty"`
	HourOpen                                    string `json:"HourOpen,omitempty"`
	IncentiveSumBaseSum                         string `json:"IncentiveSumBase.Sum,omitempty"`
	IncreasePercent                             string `json:"IncreasePercent,omitempty"`
	IncreaseSum                                 string `json:"IncreaseSum,omitempty"`
	JurName                                     string `json:"JurName,omitempty"`
	Mounth                                      string `json:"Mounth,omitempty"`
	NonCashPaymentType                          string `json:"NonCashPaymentType,omitempty"`
	NonCashPaymentTypeDocumentType              string `json:"NonCashPaymentType.DocumentType,omitempty"`
	OpenDateTyped                               string `json:"OpenDate.Typed,omitempty"` // also spelled OpenDate, OpenDate.OperDayFilter
	OpenTime                                    string `json:"OpenTime,omitempty"`
	OperationType                               string `json:"OperationType,omitempty"`
	OrderDeleted                                string `json:"OrderDeleted,omitempty"`
	OrderDiscountGuestCard                      string `json:"OrderDiscount.GuestCard,omitempty"`
	OrderDiscountType                           string `json:"OrderDiscount.Type,omitempty"`
	OrderIncreaseType                           string `json:"OrderIncrease.Type,omitempty"`
	OrderItems                                  string `json:"OrderItems,omitempty"`
	OrderNum                                    string `json:"OrderNum,omitempty"`
	OrderTimeAverageOrderTime                   string `json:"OrderTime.AverageOrderTime,omitempty"`
	OrderTimeAveragePrechequeTime               string `json:"OrderTime.AveragePrechequeTime,omitempty"`
	OrderTimeOrderLength                        string `json:"OrderTime.OrderLength,omitempty"`
	OrderTimeOrderLengthSum                     string `json:"OrderTime.OrderLengthSum,omitempty"`
	OrderTimePrechequeLength                    string `json:"OrderTime.PrechequeLength,omitempty"`
	OrderType                                   string `json:"OrderType,omitempty"`
	OrderWaiterName                             string `json:"OrderWaiter.Name,omitempty"`
	OriginName                                  string `json:"OriginName,omitempty"`
	PayTypes                                    string `json:"PayTypes,omitempty"`
	PayTypesCombo                               string `json:"PayTypes.Combo,omitempty"`
	PayTypesGroup                               string `json:"PayTypes.Group,omitempty"`
	PayTypesIsPrintCheque                       string `json:"PayTypes.IsPrintCheque,omitempty"`
	PayTypesVoucherNum                          string `json:"PayTypes.VoucherNum,omitempty"`
	PercentOfSummaryByCol                       string `json:"PercentOfSummary.ByCol,omitempty"`
	PercentOfSummaryByRow                       string `json:"PercentOfSummary.ByRow,omitempty"`
	PrechequeTime                               string `json:"PrechequeTime,omitempty"`
	PriceCategory                               string `json:"PriceCategory,omitempty"`
	PriceCategoryCard                           string `json:"PriceCategoryCard,omitempty"`
	PriceCategoryDiscountCardOwner              string `json:"PriceCategoryDiscountCardOwner,omitempty"`
	PriceCategoryUserCardOwner                  string `json:"PriceCategoryUserCardOwner,omitempty"`
	ProductCostBaseMarkUp                       string `json:"ProductCostBase.MarkUp,omitempty"`
	ProductCostBaseOneItem                      string `json:"ProductCostBase.OneItem,omitempty"`
	ProductCostBasePercent                      string `json:"ProductCostBase.Percent,omitempty"`
	ProductCostBaseProductCost                  string `json:"ProductCostBase.ProductCost,omitempty"`
	ProductCostBaseProfit                       string `json:"ProductCostBase.Profit,omitempty"`
	RemovalType                                 string `json:"RemovalType,omitempty"`
	RestaurantSection                           string `json:"RestaurantSection,omitempty"`
	RestorauntGroup                             string `json:"RestorauntGroup,omitempty"`
	SessionNum                                  string `json:"SessionNum,omitempty"`
	SoldWithDish                                string `json:"SoldWithDish,omitempty"`
	StoreName                                   string `json:"Store.Name,omitempty"`
	StoreTo                                     string `json:"StoreTo,omitempty"`
	Storned                                     string `json:"Storned,omitempty"`
	SumAfterDiscountWithoutVAT                  string `json:"sumAfterDiscountWithoutVAT,omitempty"`
	TableNum                                    string `json:"TableNum,omitempty"` // also spelled TableNumInt
	UniqOrderID                                 string `json:"UniqOrderId,omitempty"`
	UniqOrderIDOrdersCount                      string `json:"UniqOrderId.OrdersCount,omitempty"`
	VATPercent                                  string `json:"VAT.Percent,omitempty"`
	VATSum                                      string `json:"VAT.Sum,omitempty"`
	WaiterName                                  string `json:"WaiterName,omitempty"`
	WriteoffReason                              string `json:"WriteoffReason,omitempty"`
	WriteoffUser                                string `json:"WriteoffUser,omitempty"`
	YearOpen                                    string `json:"YearOpen,omitempty"`
}

// UnmarshalJSON accepts every documented spelling of OlapFieldsSales's ambiguous fields.
func (x *OlapFieldsSales) UnmarshalJSON(data []byte) error {
	type plain OlapFieldsSales
	var v struct {
		plain
		Alias0_0 string `json:"OpenDate"`
		Alias0_1 string `json:"OpenDate.OperDayFilter"`
		Alias1_0 string `json:"TableNumInt"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = OlapFieldsSales(v.plain)
	if x.OpenDateTyped == "" {
		x.OpenDateTyped = v.Alias0_0
	}
	if x.OpenDateTyped == "" {
		x.OpenDateTyped = v.Alias0_1
	}
	if x.TableNum == "" {
		x.TableNum = v.Alias1_0
	}
	return nil
}

// OlapFieldsStock mirrors the iiko DTO of the same name.
type OlapFieldsStock struct {
	ProductNum                 string `json:"ProductNum,omitempty"`
	ProductName                string `json:"ProductName,omitempty"`
	ProductAccountingCategory  string `json:"ProductAccountingCategory,omitempty"`
	EventDate                  string `json:"EventDate,omitempty"`
	EventCookingDate           string `json:"EventCookingDate,omitempty"`
	ProductMeasureUnit         string `json:"ProductMeasureUnit,omitempty"`
	ProductCategory            string `json:"ProductCategory,omitempty"`
	DepartmentCode             string `json:"Department.Code,omitempty"`
	Amount                     string `json:"Amount,omitempty"`
	ProductExpirationDuration  string `json:"ProductExpirationDuration,omitempty"`
	ProductCostBaseOneItem     string `json:"ProductCostBase.OneItem,omitempty"`
	ProductCostBaseProductCost string `json:"ProductCostBase.ProductCost,omitempty"`
	StoreFrom                  string `json:"StoreFrom,omitempty"`
	User                       string `json:"User,omitempty"`
	AccountTo                  string `json:"AccountTo,omitempty"`
	EventType                  string `json:"Event.Type,omitempty"`
	Department                 string `json:"Department,omitempty"`
}

// OlapFieldsTransactions mirrors the iiko DTO of the same name.
type OlapFieldsTransactions struct {
	AccountAccountHierarchyFull     string `json:"Account.AccountHierarchyFull,omitempty"`
	AccountAccountHierarchySecond   string `json:"Account.AccountHierarchySecond,omitempty"`
	AccountAccountHierarchyThird    string `json:"Account.AccountHierarchyThird,omitempty"`
	AccountAccountHierarchyTop      string `json:"Account.AccountHierarchyTop,omitempty"`
	AccountCode                     string `json:"Account.Code,omitempty"`
	AccountCounteragentType         string `json:"Account.CounteragentType,omitempty"`
	AccountGroup                    string `json:"Account.Group,omitempty"`
	AccountIsCashFlowAccount        string `json:"Account.IsCashFlowAccount,omitempty"`
	AccountName                     string `json:"Account.Name,omitempty"`
	AccountStoreOrAccount           string `json:"Account.StoreOrAccount,omitempty"`
	AccountType                     string `json:"Account.Type,omitempty"`
	Amount                          string `json:"Amount,omitempty"`
	AmountIn                        string `json:"Amount.In,omitempty"`
	AmountOut                       string `json:"Amount.Out,omitempty"`
	AmountStoreInOutTyped           string `json:"Amount.StoreInOutTyped,omitempty"` // also spelled Amount.StoreInOut
	CashFlowCategory                string `json:"CashFlowCategory,omitempty"`
	CashFlowCategoryHierarchy       string `json:"CashFlowCategory.Hierarchy,omitempty"`
	CashFlowCategoryHierarchyLevel1 string `json:"CashFlowCategory.HierarchyLevel1,omitempty"`
	CashFlowCategoryHierarchyLevel2 string `json:"CashFlowCategory.HierarchyLevel2,omitempty"`
	CashFlowCategoryHierarchyLevel3 string `json:"CashFlowCategory.HierarchyLevel3,omitempty"`
	CashFlowCategoryType            string `json:"CashFlowCategory.Type,omitempty"`
	Comment                         string `json:"Comment,omitempty"`
	Conception                      string `json:"Conception,omitempty"`
	ConceptionCode                  string `json:"Conception.Code,omitempty"`
	ContrAccountCode                string `json:"Contr-Account.Code,omitempty"`
	ContrAccountGroup               string `json:"Contr-Account.Group,omitempty"`
	ContrAccountName                string `json:"Contr-Account.Name,omitempty"`
	ContrAccountType                string `json:"Contr-Account.Type,omitempty"`
	ContrAmount                     string `json:"Contr-Amount,omitempty"`
	ContrProductAccountingCategory  string `json:"Contr-Product.AccountingCategory,omitempty"`
	ContrProductAlcoholClass        string `json:"Contr-Product.AlcoholClass,omitempty"`
	ContrProductAlcoholClassCode    string `json:"Contr-Product.AlcoholClass.Code,omitempty"`
	ContrProductAlcoholClassGroup   string `json:"Contr-Product.AlcoholClass.Group,omitempty"`
	ContrProductAlcoholClassType    string `json:"Contr-Product.AlcoholClass.Type,omitempty"`
	ContrProductCategory            string `json:"Contr-Product.Category,omitempty"`
	ContrProductCookingPlaceType    string `json:"Contr-Product.CookingPlaceType,omitempty"`
	ContrProductHierarchy           string `json:"Contr-Product.Hierarchy,omitempty"`
	ContrProductMeasureUnit         string `json:"Contr-Product.MeasureUnit,omitempty"`
	ContrProductName                string `json:"Contr-Product.Name,omitempty"`
	ContrProductNum                 string `json:"Contr-Product.Num,omitempty"`
	ContrProductSecondParent        string `json:"Contr-Product.SecondParent,omitempty"`
	ContrProductThirdParent         string `json:"Contr-Product.ThirdParent,omitempty"`
	ContrProductTopParent           string `json:"Contr-Product.TopParent,omitempty"`
	ContrProductType                string `json:"Contr-Product.Type,omitempty"`
	CounteragentName                string `json:"Counteragent.Name,omitempty"`
	DateTimeTyped                   string `json:"DateTime.Typed,omitempty"`     // also spelled DateTime
	DateTimeDateTyped               string `json:"DateTime.DateTyped,omitempty"` // also spelled DateTime.Date, DateTime.OperDayFilter
	DateTimeDayOfWeak               string `json:"DateTime.DayOfWeak,omitempty"`
	DateTimeHour                    string `json:"DateTime.Hour,omitempty"`
	DateTimeMonth                   string `json:"DateTime.Month,omitempty"`
	DateTimeYear                    string `json:"DateTime.Year,omitempty"`
	DateSecondaryDateTyped          string `json:"DateSecondary.DateTyped,omitempty"`
	DateSecondaryDateTimeTyped      string `json:"DateSecondary.DateTimeTyped,omitempty"`
	Department                      string `json:"Department,omitempty"`
	DepartmentCategory1             string `json:"Department.Category1,omitempty"`
	DepartmentCategory2             string `json:"Department.Category2,omitempty"`
	DepartmentCategory3             string `json:"Department.Category3,omitempty"`
	DepartmentCategory4             string `json:"Department.Category4,omitempty"`
	DepartmentCategory5             string `json:"Department.Category5,omitempty"`
	DepartmentCode                  string `json:"Department.Code,omitempty"`
	DepartmentJurPerson             string `json:"Department.JurPerson,omitempty"`
	Document                        string `json:"Document,omitempty"`
	FinalBalanceAmount              string `json:"FinalBalance.Amount,omitempty"`
	FinalBalanceMoney               string `json:"FinalBalance.Money,omitempty"`
	PercentOfSummaryByCol           string `json:"PercentOfSummary.ByCol,omitempty"`
	PercentOfSummaryByRow           string `json:"PercentOfSummary.ByRow,omitempty"`
	ProductAccountingCategory       string `json:"Product.AccountingCategory,omitempty"`
	ProductAlcoholClass             string `json:"Product.AlcoholClass,omitempty"`
	ProductAlcoholClassCode         string `json:"Product.AlcoholClass.Code,omitempty"`
	ProductAlcoholClassGroup        string `json:"Product.AlcoholClass.Group,omitempty"`
	ProductAlcoholClassType         string `json:"Product.AlcoholClass.Type,omitempty"`
	ProductAvgSum                   string `json:"Product.AvgSum,omitempty"`
	ProductCategory                 string `json:"Product.Category,omitempty"`
	ProductCookingPlaceType         string `json:"Product.CookingPlaceType,omitempty"`
	ProductHierarchy                string `json:"Product.Hierarchy,omitempty"`
	ProductMeasureUnit              string `json:"Product.MeasureUnit,omitempty"`
	ProductName                     string `json:"Product.Name,omitempty"`
	ProductNum                      string `json:"Product.Num,omitempty"`
	ProductSecondParent             string `json:"Product.SecondParent,omitempty"`
	ProductThirdParent              string `json:"Product.ThirdParent,omitempty"`
	ProductTopParent                string `json:"Product.TopParent,omitempty"`
	ProductType                     string `json:"Product.Type,omitempty"`
	SessionCashRegister             string `json:"Session.CashRegister,omitempty"`
	SessionGroup                    string `json:"Session.Group,omitempty"`
	SessionRestaurantSection        string `json:"Session.RestaurantSection,omitempty"`
	StartBalanceAmount              string `json:"StartBalance.Amount,omitempty"`
	StartBalanceMoney               string `json:"StartBalance.Money,omitempty"`
	Store                           string `json:"Store,omitempty"`
	SumIncoming                     string `json:"Sum.Incoming,omitempty"`
	SumOutgoing                     string `json:"Sum.Outgoing,omitempty"`
	SumPartOfIncome                 string `json:"Sum.PartOfIncome,omitempty"`
	SumPartOfSummaryByCol           string `json:"Sum.PartOfSummaryByCol,omitempty"`
	SumPartOfSummaryByRow           string `json:"Sum.PartOfSummaryByRow,omitempty"`
	SumPartOfTotalIncome            string `json:"Sum.PartOfTotalIncome,omitempty"`
	SumResignedSum                  string `json:"Sum.ResignedSum,omitempty"`
	TransactionSide                 string `json:"TransactionSide,omitempty"`
	TransactionType                 string `json:"TransactionType,omitempty"`
	TransactionTypeCode             string `json:"TransactionType.Code,omitempty"`
}

// UnmarshalJSON accepts every documented spelling of OlapFieldsTransactions's ambiguous fields.
func (x *OlapFieldsTransactions) UnmarshalJSON(data []byte) error {
	type plain OlapFieldsTransactions
	var v struct {
		plain
		Alias0_0 string `json:"Amount.StoreInOut"`
		Alias1_0 string `json:"DateTime"`
		Alias2_0 string `json:"DateTime.Date"`
		Alias2_1 string `json:"DateTime.OperDayFilter"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = OlapFieldsTransactions(v.plain)
	if x.AmountStoreInOutTyped == "" {
		x.AmountStoreInOutTyped = v.Alias0_0
	}
	if x.DateTimeTyped == "" {
		x.DateTimeTyped = v.Alias1_0
	}
	if x.DateTimeDateTyped == "" {
		x.DateTimeDateTyped = v.Alias2_0
	}
	if x.DateTimeDateTyped == "" {
		x.DateTimeDateTyped = v.Alias2_1
	}
	return nil
}

// OlapFilter is Not a DTO the docs name; the OLAP v2 request body's `filters` is a map of column name -> one of three differen…
type OlapFilter struct {
	FilterType string `json:"filterType"` // IncludeValues ExcludeValues Range DateRange
}

// OlapFilterDateRangeOlapDateRangeFilterTypeValues are the documented values of OlapFilterDateRange.OlapDateRangeFilterType.
var OlapFilterDateRangeOlapDateRangeFilterTypeValues = []string{
	"DateRange",
}

// OlapFilterDateRangeOlapPeriodTypeValues are the documented values of OlapFilterDateRange.OlapPeriodType.
var OlapFilterDateRangeOlapPeriodTypeValues = []string{
	"CUSTOM",
	"OPEN_PERIOD",
	"TODAY",
	"YESTERDAY",
	"CURRENT_WEEK",
	"CURRENT_MONTH",
	"CURRENT_YEAR",
	"LAST_WEEK",
	"LAST_MONTH",
	"LAST_YEAR",
}

// OlapFilterDateRange mirrors the iiko DTO of the same name.
type OlapFilterDateRange struct {
	FilterType  string `json:"filterType"`
	PeriodType  string `json:"periodType"`
	From        string `json:"from"`
	To          string `json:"to,omitempty"`
	IncludeLow  bool   `json:"includeLow,omitempty"`
	IncludeHigh bool   `json:"includeHigh,omitempty"`
}

// OlapFilterIncludeExcludeValuesOlapIncludeExcludeFilterTypeValues are the documented values of OlapFilterIncludeExcludeValues.OlapIncludeExcludeFilterType.
var OlapFilterIncludeExcludeValuesOlapIncludeExcludeFilterTypeValues = []string{
	"IncludeValues",
	"ExcludeValues",
}

// OlapFilterIncludeExcludeValues mirrors the iiko DTO of the same name.
type OlapFilterIncludeExcludeValues struct {
	FilterType string   `json:"filterType"`
	Values     []string `json:"values"`
}

// OlapFilterRangeOlapRangeFilterTypeValues are the documented values of OlapFilterRange.OlapRangeFilterType.
var OlapFilterRangeOlapRangeFilterTypeValues = []string{
	"Range",
}

// OlapFilterRange mirrors the iiko DTO of the same name.
type OlapFilterRange struct {
	FilterType  string  `json:"filterType"`
	From        float64 `json:"from"`
	To          float64 `json:"to"`
	IncludeLow  bool    `json:"includeLow,omitempty"`
	IncludeHigh bool    `json:"includeHigh,omitempty"`
}

// OlapPreset mirrors the iiko DTO of the same name.
type OlapPreset struct {
	ID               string                `json:"id"`
	Name             string                `json:"name"`
	ReportType       string                `json:"reportType,omitempty"`
	GroupByRowFields []string              `json:"groupByRowFields,omitempty"`
	GroupByColFields []string              `json:"groupByColFields,omitempty"`
	AggregateFields  []string              `json:"aggregateFields,omitempty"`
	Filters          map[string]OlapFilter `json:"filters,omitempty"`
}

// OlapReportTypeOlapReportTypeV2Values are the documented values of OlapReportType.OlapReportTypeV2.
var OlapReportTypeOlapReportTypeV2Values = []string{
	"SALES",
	"TRANSACTIONS",
	"DELIVERIES",
}

// OlapV2RequestBody mirrors the iiko DTO of the same name.
type OlapV2RequestBody struct {
	ReportType       string                `json:"reportType"`
	BuildSummary     bool                  `json:"buildSummary,omitempty"`
	GroupByRowFields []string              `json:"groupByRowFields"`
	GroupByColFields []string              `json:"groupByColFields,omitempty"`
	AggregateFields  []string              `json:"aggregateFields"`
	Filters          map[string]OlapFilter `json:"filters,omitempty"`
}

// OlapV2Response mirrors the iiko DTO of the same name.
type OlapV2Response struct {
	Data    []json.RawMessage `json:"data"`
	Summary []json.RawMessage `json:"summary"`
}

// OperationTypeOperationTypeValues are the documented values of OperationType.OperationType.
var OperationTypeOperationTypeValues = []string{
	"STORNED",
	"PREPAY",
	"PREPAY_RETURN",
	"NO_PAYMENT",
	"PAYMENT",
}

// OrderDeletedFlagOrderDeletedFlagValues are the documented values of OrderDeletedFlag.OrderDeletedFlag.
var OrderDeletedFlagOrderDeletedFlagValues = []string{
	"NOT_DELETED",
	"DELETED",
}

// PaymentFiscalFlagPaymentFiscalFlagValues are the documented values of PaymentFiscalFlag.PaymentFiscalFlag.
var PaymentFiscalFlagPaymentFiscalFlagValues = []string{
	"FISCAL",
	"NOT_FISCAL",
	"NO_PAYMENT",
}

// PaymentGroupPaymentGroupValues are the documented values of PaymentGroup.PaymentGroup.
var PaymentGroupPaymentGroupValues = []string{
	"CASH",
	"CARD",
	"WRITEOFF",
	"NON_CASH",
}

// ProductGroupTypeProductGroupTypeValues are the documented values of ProductGroupType.ProductGroupType.
var ProductGroupTypeProductGroupTypeValues = []string{
	"PRODUCTS",
	"MODIFIERS",
}

// ProductTypeProductTypeValues are the documented values of ProductType.ProductType.
var ProductTypeProductTypeValues = []string{
	"GOODS",
	"DISH",
	"PREPARED",
	"SERVICE",
	"MODIFIER",
	"OUTER",
	"PETROL",
	"RATE",
}

// StoreOperationsReportGroupingDateDetalizationValues are the documented values of StoreOperationsReportGrouping.DateDetalization.
var StoreOperationsReportGroupingDateDetalizationValues = []string{
	"DAY",
	"YEAR",
	"MONTH",
	"WEEK",
	"HALF_MONTH",
	"TOTAL_ONLY",
	"QUARTER",
}

// StoreOperationsReportGrouping mirrors the iiko DTO of the same name.
type StoreOperationsReportGrouping struct {
	DateDetalization string `xml:"dateDetalization,omitempty"`
}

// StoreOrAccountStoreOrAccountValues are the documented values of StoreOrAccount.StoreOrAccount.
var StoreOrAccountStoreOrAccountValues = []string{
	"STORE",
	"ACCOUNT",
}

// StoreReportItemDtoTransactionTypeValues are the documented values of StoreReportItemDto.TransactionType.
var StoreReportItemDtoTransactionTypeValues = []string{
	"OPENING_BALANCE",
	"CUSTOM",
	"CASH",
	"PREPAY_CLOSED",
	"PREPAY",
	"PREPAY_RETURN",
	"PREPAY_CLOSED_RETURN",
	"DISCOUNT",
	"CARD",
	"CREDIT",
	"PAYIN",
	"PAYOUT",
	"PAY_COLLECTION",
	"CASH_CORRECTION",
	"INVENTORY_CORRECTION",
	"STORE_COST_CORRECTION",
	"CASH_SURPLUS",
	"CASH_SHORTAGE",
	"PENALTY",
	"BONUS",
	"INVOICE",
	"NDS_INCOMING",
	"NDS_SALES",
	"SALES_REVENUE",
	"OUTGOING_INVOICE",
	"OUTGOING_INVOICE_REVENUE",
	"RETURNED_INVOICE",
	"RETURNED_INVOICE_REVENUE",
	"WRITEOFF",
	"SESSION_WRITEOFF",
	"TRANSFER",
	"TRANSFORMATION",
	"TARIFF_HOUR",
	"ON_THE_HOUSE",
	"ADVANCE",
	"INCOMING_SERVICE",
	"OUTGOING_SERVICE",
	"INCOMING_SERVICE_PAYMENT",
	"OUTGOING_SERVICE_PAYMENT",
	"CLOSE_AT_EMPLOYEE_EXPENSE",
	"INCENTIVE_PAYMENT",
	"TARIFF_PERCENT",
	"SESSION_ACCEPTANCE",
	"EMPLOYEE_CASH_PAYMENT",
	"EMPLOYEE_PAYMENT",
	"INVOICE_PAYMENT",
	"OUTGOING_DOCUMENT_PAYMENT",
	"OUTGOING_SALES_DOCUMENT_PAYMENT",
	"PRODUCTION",
	"SALES_RETURN_PAYMENT",
	"SALES_RETURN_WRITEOFF",
	"DISASSEMBLE",
}

// StoreReportItemDtoDocumentTypeValues are the documented values of StoreReportItemDto.DocumentType.
var StoreReportItemDtoDocumentTypeValues = []string{
	"INCOMING_INVOICE",
	"INCOMING_INVENTORY",
	"INCOMING_SERVICE",
	"OUTGOING_SERVICE",
	"WRITEOFF_DOCUMENT",
	"SALES_DOCUMENT",
	"SESSION_ACCEPTANCE",
	"INTERNAL_TRANSFER",
	"OUTGOING_INVOICE",
	"RETURNED_INVOICE",
	"PRODUCTION_DOCUMENT",
	"TRANSFORMATION_DOCUMENT",
	"PRODUCTION_ORDER",
	"CONSOLIDATED_ORDER",
	"PREPARED_REGISTER",
	"MENU_CHANGE",
	"PRODUCT_REPLACEMENT",
	"SALES_RETURN_DOCUMENT",
	"DISASSEMBLE_DOCUMENT",
	"FUEL_ACCEPTANCE",
	"FUEL_GAGING_DOCUMENT",
	"PAYROLL",
}

// StoreReportItemDto mirrors the iiko DTO of the same name.
type StoreReportItemDto struct {
	NDSPercent                   float64 `xml:"ndsPercent,omitempty"`
	ProductCategory              string  `xml:"productCategory,omitempty"`
	ProductGroup                 string  `xml:"productGroup,omitempty"`
	Product                      string  `xml:"product,omitempty"`
	SecondaryAccount             string  `xml:"secondaryAccount,omitempty"`
	PrimaryStore                 string  `xml:"primaryStore,omitempty"`
	DocumentNum                  string  `xml:"documentNum,omitempty"`
	ExpenseAccount               string  `xml:"expenseAccount,omitempty"`
	RevenueAccount               string  `xml:"revenueAccount,omitempty"`
	DocumentComment              string  `xml:"documentComment,omitempty"`
	DocumentID                   string  `xml:"documentId,omitempty"`
	DocumentType                 string  `xml:"documentType,omitempty"`
	Incoming                     bool    `xml:"incoming"`
	Type                         string  `xml:"type,omitempty"`
	Date                         string  `xml:"date,omitempty"`
	OperationalDate              string  `xml:"operationalDate,omitempty"`
	Cost                         float64 `xml:"cost,omitempty"`
	SecondEstimatedPurchasePrice float64 `xml:"secondEstimatedPurchasePrice,omitempty"`
	FirstEstimatedPurchasePrice  float64 `xml:"firstEstimatedPurchasePrice,omitempty"`
	DocumentSum                  float64 `xml:"documentSum,omitempty"`
	SecondaryAmount              float64 `xml:"secondaryAmount,omitempty"`
	Amount                       float64 `xml:"amount,omitempty"`
	SumWithoutNDS                float64 `xml:"sumWithoutNds,omitempty"`
	SumNDS                       float64 `xml:"sumNds,omitempty"`
	Sum                          float64 `xml:"sum,omitempty"`
}

// StoreReportPreset mirrors the iiko DTO of the same name.
type StoreReportPreset struct {
	ID             string                        `xml:"id,omitempty"`
	DefaultReport  bool                          `xml:"defaultReport"`
	Name           string                        `xml:"name,omitempty"`
	Comment        string                        `xml:"comment,omitempty"`
	Grouping       StoreOperationsReportGrouping `xml:"grouping,omitempty"`
	Filter         StoreReportPresetFilter       `xml:"filter,omitempty"`
	ColumnCaptions []KeyValue                    `xml:"columnCaptions,omitempty"`
}

// StoreReportPresetFilterTransactionTypeValues are the documented values of StoreReportPresetFilter.TransactionType.
var StoreReportPresetFilterTransactionTypeValues = []string{
	"SESSION_WRITEOFF",
	"OUTGOING_SALES_DOCUMENT_PAYMENT",
	"PREPAY_CLOSED",
	"CASH_SURPLUS",
	"RETURNED_INVOICE",
	"CREDIT",
	"CASH_SHORTAGE",
	"OUTGOING_SERVICE",
	"STORE_COST_CORRECTION",
	"SALES_REVENUE",
	"ADVANCE",
	"PAYOUT",
	"INVOICE_PAYMENT",
	"OUTGOING_DOCUMENT_PAYMENT",
	"TARIFF_HOUR",
	"TRANSFER",
	"WRITEOFF",
	"SALES_RETURN_WRITEOFF",
	"CARD",
	"PREPAY_CLOSED_RETURN",
	"PRODUCTION",
	"EMPLOYEE_CASH_PAYMENT",
	"DISCOUNT",
	"OUTGOING_INVOICE",
	"INVENTORY_CORRECTION",
	"IMPORTED_BANK_STATEMENT",
	"INCENTIVE_PAYMENT",
	"NDS_INCOMING",
	"DISASSEMBLE",
	"CASH",
	"OPENING_BALANCE",
	"INCOMING_SERVICE",
	"TRANSFORMATION",
	"BONUS",
	"SESSION_ACCEPTANCE",
	"PREPAY_RETURN",
	"ON_THE_HOUSE",
	"EMPLOYEE_PAYMENT",
	"SALES_RETURN_PAYMENT",
	"INVOICE",
	"PENALTY",
	"OUTGOING_SERVICE_PAYMENT",
	"CLOSE_AT_EMPLOYEE_EXPENSE",
	"PAY_COLLECTION",
	"TARIFF_PERCENT",
	"INCOMING_SERVICE_PAYMENT",
	"PAYIN",
	"RETURNED_INVOICE_REVENUE",
	"NDS_SALES",
	"OUTGOING_INVOICE_REVENUE",
	"PREPAY",
	"CUSTOM",
	"CASH_CORRECTION",
}

// StoreReportPresetFilterDocumentTypeValues are the documented values of StoreReportPresetFilter.DocumentType.
var StoreReportPresetFilterDocumentTypeValues = []string{
	"INCOMING_INVOICE",
	"INTERNAL_TRANSFER",
	"TRANSFORMATION_DOCUMENT",
	"PAYROLL",
	"DISASSEMBLE_DOCUMENT",
	"OUTGOING_INVOICE",
	"MENU_CHANGE",
	"OUTGOING_CASH_ORDER",
	"PREPARED_REGISTER",
	"SALES_RETURN_DOCUMENT",
	"INCOMING_CASH_ORDER",
	"SALES_DOCUMENT",
	"WRITEOFF_DOCUMENT",
	"PRODUCTION_ORDER",
	"FUEL_ACCEPTANCE",
	"PRODUCTION_DOCUMENT",
	"PRODUCT_REPLACEMENT",
	"SESSION_ACCEPTANCE",
	"RETURNED_INVOICE",
	"INCOMING_SERVICE",
	"FUEL_GAGING_DOCUMENT",
	"CONSOLIDATED_ORDER",
	"OUTGOING_SERVICE",
	"INCOMING_INVENTORY",
}

// StoreReportPresetFilterStoreDataDirectionValues are the documented values of StoreReportPresetFilter.StoreDataDirection.
var StoreReportPresetFilterStoreDataDirectionValues = []string{
	"IN",
	"INOUT",
	"OUT",
}

// StoreReportPresetFilter mirrors the iiko DTO of the same name.
type StoreReportPresetFilter struct {
	PrimaryStores           []string `xml:"primaryStores,omitempty"`
	SecondaryAccounts       []string `xml:"secondaryAccounts,omitempty"`
	Counteragents           []string `xml:"counteragents,omitempty"`
	Products                []string `xml:"products,omitempty"`
	SecondaryProducts       []string `xml:"secondaryProducts,omitempty"`
	TransactionTypes        []string `xml:"transactionTypes,omitempty"`
	DocumentTypes           []string `xml:"documentTypes,omitempty"`
	DataDirection           string   `xml:"dataDirection,omitempty"`
	IncludeZeroAmountAndSum bool     `xml:"includeZeroAmountAndSum"`
}

// TransactionSideTransactionSideValues are the documented values of TransactionSide.TransactionSide.
var TransactionSideTransactionSideValues = []string{
	"DEBIT",
	"CREDIT",
}

// TransactionTypeTransactionTypeValues are the documented values of TransactionType.TransactionType.
var TransactionTypeTransactionTypeValues = []string{
	"OPENING_BALANCE",
	"CUSTOM",
	"CASH",
	"PREPAY_CLOSED",
	"PREPAY",
	"PREPAY_RETURN",
	"PREPAY_CLOSED_RETURN",
	"DISCOUNT",
	"CARD",
	"CREDIT",
	"PAYIN",
	"PAYOUT",
	"PAY_COLLECTION",
	"CASH_CORRECTION",
	"INVENTORY_CORRECTION",
	"STORE_COST_CORRECTION",
	"CASH_SURPLUS",
	"CASH_SHORTAGE",
	"PENALTY",
	"BONUS",
	"INVOICE",
	"NDS_INCOMING",
	"NDS_SALES",
	"SALES_REVENUE",
	"OUTGOING_INVOICE",
	"OUTGOING_INVOICE_REVENUE",
	"RETURNED_INVOICE",
	"RETURNED_INVOICE_REVENUE",
	"WRITEOFF",
	"SESSION_WRITEOFF",
	"TRANSFER",
	"TRANSFORMATION",
	"TARIFF_HOUR",
	"ON_THE_HOUSE",
	"ADVANCE",
	"INCOMING_SERVICE",
	"OUTGOING_SERVICE",
	"INCOMING_SERVICE_PAYMENT",
	"OUTGOING_SERVICE_PAYMENT",
	"IMPORTED_BANK_STATEMENT",
	"CLOSE_AT_EMPLOYEE_EXPENSE",
	"INCENTIVE_PAYMENT",
	"TARIFF_PERCENT",
	"SESSION_ACCEPTANCE",
	"EMPLOYEE_CASH_PAYMENT",
	"EMPLOYEE_PAYMENT",
	"INVOICE_PAYMENT",
	"OUTGOING_DOCUMENT_PAYMENT",
	"OUTGOING_SALES_DOCUMENT_PAYMENT",
	"PRODUCTION",
	"SALES_RETURN_PAYMENT",
	"SALES_RETURN_WRITEOFF",
	"DISASSEMBLE",
}
