// Package menu paths. Every path is a constant here; none appears in a method body.

package menu

const (
	addStopLists                      = "/api/1/stop_lists/add"
	calculateCombo                    = "/api/1/combo/calculate"
	checkStopLists                    = "/api/1/stop_lists/check"
	clearStopLists                    = "/api/1/stop_lists/clear"
	createNomenclatureAssemblyChart   = "/api/nomenclature/v2/assembly-chart/create"
	createNomenclatureCategory        = "/api/nomenclature/v1/nomenclature/category/create"
	createNomenclatureGroup           = "/api/nomenclature/v2/group/create"
	createNomenclatureProduct         = "/api/nomenclature/v2/product/create"
	createNomenclatureProductScale    = "/api/nomenclature/v1/product-scale/create"
	deleteNomenclatureAssemblyChart   = "/api/nomenclature/v2/assembly-chart/delete"
	deleteNomenclatureCategory        = "/api/nomenclature/v1/nomenclature/category/delete"
	deleteNomenclatureGroup           = "/api/nomenclature/v2/group/delete"
	deleteNomenclatureProduct         = "/api/nomenclature/v2/product/delete"
	deleteNomenclatureProductScale    = "/api/nomenclature/v1/product-scale/delete"
	getCombo                          = "/api/1/combo"
	getMenu                           = "/api/2/menu"
	getMenuByID                       = "/api/menu/v3/by_id"
	getNomenclatureAssemblyChart      = "/api/nomenclature/v2/assembly-chart/get"
	getNomenclatureProductScale       = "/api/nomenclature/v1/product-scale/get"
	getStopLists                      = "/api/1/stop_lists"
	listNomenclatureAllergenGroup     = "/api/nomenclature/v1/allergen-group/list"
	listNomenclatureAmountUnit        = "/api/nomenclature/v1/amount-unit/list"
	listNomenclatureAssemblyChart     = "/api/nomenclature/v2/assembly-chart/list"
	listNomenclatureCategory          = "/api/nomenclature/v1/nomenclature/category/list"
	listNomenclatureContainer         = "/api/nomenclature/v1/container/list"
	listNomenclatureCustomCategory    = "/api/nomenclature/v1/custom-category/list"
	listNomenclatureGroup             = "/api/nomenclature/v2/group/list"
	listNomenclatureMenu              = "/api/nomenclature/v1/menu/list"
	listNomenclatureModifierSchema    = "/api/nomenclature/v1/modifier-schema/list"
	listNomenclaturePlaceType         = "/api/nomenclature/v1/place-type/list"
	listNomenclatureProducer          = "/api/nomenclature/v1/producer/list"
	listNomenclatureProduct           = "/api/nomenclature/v2/product/list"
	listNomenclatureProductScale      = "/api/nomenclature/v1/product-scale/list"
	listNomenclatureProductSize       = "/api/nomenclature/v1/product-size/list"
	listNomenclatureProductTag        = "/api/nomenclature/v1/product-tag/list"
	removeStopLists                   = "/api/1/stop_lists/remove"
	restoreNomenclatureCategory       = "/api/nomenclature/v1/nomenclature/category/restore"
	restoreNomenclatureGroup          = "/api/nomenclature/v2/group/restore"
	restoreNomenclatureProduct        = "/api/nomenclature/v2/product/restore"
	updateBarcodesNomenclatureProduct = "/api/nomenclature/v2/product/update_barcodes"
	updateNomenclatureAssemblyChart   = "/api/nomenclature/v2/assembly-chart/update"
	updateNomenclatureCategory        = "/api/nomenclature/v1/nomenclature/category/update"
	updateNomenclatureGroup           = "/api/nomenclature/v2/group/update"
	updateNomenclatureProduct         = "/api/nomenclature/v2/product/update"
	updateNomenclatureProductScale    = "/api/nomenclature/v1/product-scale/update"
)
