// Package finance paths. Every path is a constant here; none appears in a method body.

package finance

const (
	cancelIncomingService    = "/api/finance/v1/incoming_service/cancel"
	cancelOutgoingService    = "/api/finance/v1/outgoing_service/cancel"
	createAccount            = "/api/finance/v1/account/create"
	createCashFlowCategory   = "/api/finance/v1/cash-flow-category/create"
	createIncomingService    = "/api/finance/v1/incoming_service/create"
	createOutgoingService    = "/api/finance/v1/outgoing_service/create"
	deleteAccount            = "/api/finance/v1/account/delete"
	deleteCashFlowCategory   = "/api/finance/v1/cash-flow-category/delete"
	getAccount               = "/api/finance/v1/account/get"
	getCashFlowCategory      = "/api/finance/v1/cash-flow-category/get"
	getIncomingService       = "/api/finance/v1/incoming_service/get"
	getOutgoingService       = "/api/finance/v1/outgoing_service/get"
	listAccount              = "/api/finance/v1/account/list"
	listAccountPosting       = "/api/finance/v1/account-posting/list"
	listAccountTransactions  = "/api/finance/v1/account_transactions/list"
	listAccountType          = "/api/finance/v1/account-type/list"
	listBalanceSheet         = "/api/finance/v1/balance-sheet/list"
	listCashFlowCategory     = "/api/finance/v1/cash-flow-category/list"
	listChartOfAccounts      = "/api/finance/v1/chart-of-accounts/list"
	listDocumentTransactions = "/api/finance/v1/document_transactions/list"
	listIncomingService      = "/api/finance/v1/incoming_service/list"
	listItemCategory         = "/api/finance/v1/item-category/list"
	listOutgoingService      = "/api/finance/v1/outgoing_service/list"
	listTaxCategory          = "/api/finance/v1/tax-category/list"
	postIncomingService      = "/api/finance/v1/incoming_service/post"
	postOutgoingService      = "/api/finance/v1/outgoing_service/post"
	restoreAccount           = "/api/finance/v1/account/restore"
	restoreCashFlowCategory  = "/api/finance/v1/cash-flow-category/restore"
	unpostIncomingService    = "/api/finance/v1/incoming_service/unpost"
	unpostOutgoingService    = "/api/finance/v1/outgoing_service/unpost"
	updateAccount            = "/api/finance/v1/account/update"
	updateCashFlowCategory   = "/api/finance/v1/cash-flow-category/update"
	updateIncomingService    = "/api/finance/v1/incoming_service/update"
	updateOutgoingService    = "/api/finance/v1/outgoing_service/update"
)
